def solve_99fa7670_one(S, I):
    return underpaint(paint(I, mapply(fork(recolor_i, color, compose(rbind(shoot, RIGHT), center)), o_g(I, R5))), mapply(fork(recolor_i, compose(color, rbind(get_nth_f, F0)), fork(connect, compose(rbind(corner, R3), rbind(get_nth_f, F0)), compose(rbind(corner, R3), rbind(get_nth_f, L1)))), pair(remove_f(recolor_i(BLACK, initset(add(shape_t(I), DOWN_LEFT))), order(insert(recolor_i(BLACK, initset(add(shape_t(I), DOWN_LEFT))), o_g(paint(I, mapply(fork(recolor_i, color, compose(rbind(shoot, RIGHT), center)), o_g(I, R5))), R5)), rbind(col_row, R1))), remove_f(get_nth_t(order(insert(recolor_i(BLACK, initset(add(shape_t(I), DOWN_LEFT))), o_g(paint(I, mapply(fork(recolor_i, color, compose(rbind(shoot, RIGHT), center)), o_g(I, R5))), R5)), rbind(col_row, R1)), F0), order(insert(recolor_i(BLACK, initset(add(shape_t(I), DOWN_LEFT))), o_g(paint(I, mapply(fork(recolor_i, color, compose(rbind(shoot, RIGHT), center)), o_g(I, R5))), R5)), rbind(col_row, R1))))))


def solve_99fa7670(S, I):
    x1 = rbind(shoot, RIGHT)
    x2 = compose(x1, center)
    x3 = fork(recolor_i, color, x2)
    x4 = o_g(I, R5)
    x5 = mapply(x3, x4)
    x6 = paint(I, x5)
    x7 = rbind(get_nth_f, F0)
    x8 = compose(color, x7)
    x9 = rbind(corner, R3)
    x10 = compose(x9, x7)
    x11 = rbind(get_nth_f, L1)
    x12 = compose(x9, x11)
    x13 = fork(connect, x10, x12)
    x14 = fork(recolor_i, x8, x13)
    x15 = shape_t(I)
    x16 = add(x15, DOWN_LEFT)
    x17 = initset(x16)
    x18 = recolor_i(BLACK, x17)
    x19 = o_g(x6, R5)
    x20 = insert(x18, x19)
    x21 = rbind(col_row, R1)
    x22 = order(x20, x21)
    x23 = remove_f(x18, x22)
    x24 = get_nth_t(x22, F0)
    x25 = remove_f(x24, x22)
    x26 = pair(x23, x25)
    x27 = mapply(x14, x26)
    O = underpaint(x6, x27)
    return O
