def solve_57aa92db_one(S, I):
    return paint(paint(I, mapply(fork(recolor_o, chain(chain(rbind(get_nth_f, F0), lbind(remove, BLACK), palette_f), rbind(toobject, I), outbox), fork(upscale_f, compose(lbind(shift, normalize_o(get_arg_rank_f(o_g(I, R3), fork(subtract, compose(rbind(get_rank, F0), fork(apply, lbind(lbind, colorcount_f), palette_f)), compose(rbind(get_rank, L1), fork(apply, lbind(lbind, colorcount_f), palette_f))), F0))), fork(subtract, rbind(corner, R0), compose(lbind(multiply, corner(sfilter_f(normalize_o(get_arg_rank_f(o_g(I, R3), fork(subtract, compose(rbind(get_rank, F0), fork(apply, lbind(lbind, colorcount_f), palette_f)), compose(rbind(get_rank, L1), fork(apply, lbind(lbind, colorcount_f), palette_f))), F0)), matcher(rbind(get_nth_f, F0), get_color_rank_f(get_arg_rank_f(o_g(I, R3), fork(subtract, compose(rbind(get_rank, F0), fork(apply, lbind(lbind, colorcount_f), palette_f)), compose(rbind(get_rank, L1), fork(apply, lbind(lbind, colorcount_f), palette_f))), F0), L1))), R0)), width_f))), width_f)), colorfilter(o_g(I, R5), get_color_rank_f(get_arg_rank_f(o_g(I, R3), fork(subtract, compose(rbind(get_rank, F0), fork(apply, lbind(lbind, colorcount_f), palette_f)), compose(rbind(get_rank, L1), fork(apply, lbind(lbind, colorcount_f), palette_f))), F0), L1)))), merge_f(o_g(I, R5)))


def solve_57aa92db(S, I):
    x1 = rbind(get_nth_f, F0)
    x2 = lbind(remove, BLACK)
    x3 = chain(x1, x2, palette_f)
    x4 = rbind(toobject, I)
    x5 = chain(x3, x4, outbox)
    x6 = o_g(I, R3)
    x7 = rbind(get_rank, F0)
    x8 = lbind(lbind, colorcount_f)
    x9 = fork(apply, x8, palette_f)
    x10 = compose(x7, x9)
    x11 = rbind(get_rank, L1)
    x12 = compose(x11, x9)
    x13 = fork(subtract, x10, x12)
    x14 = get_arg_rank_f(x6, x13, F0)
    x15 = normalize_o(x14)
    x16 = lbind(shift, x15)
    x17 = rbind(corner, R0)
    x18 = get_color_rank_f(x14, L1)
    x19 = matcher(x1, x18)
    x20 = sfilter_f(x15, x19)
    x21 = corner(x20, R0)
    x22 = lbind(multiply, x21)
    x23 = compose(x22, width_f)
    x24 = fork(subtract, x17, x23)
    x25 = compose(x16, x24)
    x26 = fork(upscale_f, x25, width_f)
    x27 = fork(recolor_o, x5, x26)
    x28 = o_g(I, R5)
    x29 = colorfilter(x28, x18)
    x30 = mapply(x27, x29)
    x31 = paint(I, x30)
    x32 = merge_f(x28)
    O = paint(x31, x32)
    return O
