def solve_72322fa7_one(S, I):
    return paint(paint(I, mapply(fork(mapply, compose(lbind(lbind, shift), normalize), compose(lbind(occurrences, I), fork(sfilter, identity, compose(lbind(matcher, rbind(get_nth_f, F0)), rbind(get_color_rank_f, F0))))), difference(o_g(I, R3), sfilter_f(o_g(I, R3), matcher(numcolors_f, BLUE))))), mapply(fork(mapply, compose(lbind(lbind, shift), normalize), fork(apply, compose(lbind(rbind, add), fork(subtract, rbind(corner, R0), compose(rbind(corner, R0), fork(difference, identity, fork(sfilter, identity, compose(lbind(matcher, rbind(get_nth_f, F0)), rbind(get_color_rank_f, F0))))))), compose(lbind(occurrences, I), fork(difference, identity, fork(sfilter, identity, compose(lbind(matcher, rbind(get_nth_f, F0)), rbind(get_color_rank_f, F0))))))), difference(o_g(I, R3), sfilter_f(o_g(I, R3), matcher(numcolors_f, BLUE)))))


def solve_72322fa7(S, I):
    x1 = lbind(lbind, shift)
    x2 = compose(x1, normalize)
    x3 = lbind(occurrences, I)
    x4 = rbind(get_nth_f, F0)
    x5 = lbind(matcher, x4)
    x6 = rbind(get_color_rank_f, F0)
    x7 = compose(x5, x6)
    x8 = fork(sfilter, identity, x7)
    x9 = compose(x3, x8)
    x10 = fork(mapply, x2, x9)
    x11 = o_g(I, R3)
    x12 = matcher(numcolors_f, BLUE)
    x13 = sfilter_f(x11, x12)
    x14 = difference(x11, x13)
    x15 = mapply(x10, x14)
    x16 = paint(I, x15)
    x17 = lbind(rbind, add)
    x18 = rbind(corner, R0)
    x19 = fork(difference, identity, x8)
    x20 = compose(x18, x19)
    x21 = fork(subtract, x18, x20)
    x22 = compose(x17, x21)
    x23 = compose(x3, x19)
    x24 = fork(apply, x22, x23)
    x25 = fork(mapply, x2, x24)
    x26 = mapply(x25, x14)
    O = paint(x16, x26)
    return O
