def solve_a78176bb_one(S, I):
    return replace(fill(I, other_f(remove(BLACK, palette_t(I)), c_iz_n(S, identity(p_g), rbind(get_nth_t, F0))), combine_f(mapply(fork(combine, rbind(shoot, UNITY), rbind(shoot, NEG_UNITY)), apply(rbind(add, UP_RIGHT), apply(rbind(corner, R1), sfilter_f(colorfilter(o_g(I, R5), c_iz_n(S, identity(p_g), rbind(get_nth_t, F0))), matcher(compose(lbind(index, I), rbind(corner, R1)), c_iz_n(S, identity(p_g), rbind(get_nth_t, F0))))))), mapply(fork(combine, rbind(shoot, UNITY), rbind(shoot, NEG_UNITY)), apply(rbind(add, DOWN_LEFT), apply(rbind(corner, R2), difference(colorfilter(o_g(I, R5), c_iz_n(S, identity(p_g), rbind(get_nth_t, F0))), sfilter_f(colorfilter(o_g(I, R5), c_iz_n(S, identity(p_g), rbind(get_nth_t, F0))), matcher(compose(lbind(index, I), rbind(corner, R1)), c_iz_n(S, identity(p_g), rbind(get_nth_t, F0)))))))))), c_iz_n(S, identity(p_g), rbind(get_nth_t, F0)), BLACK)


def solve_a78176bb(S, I):
    x1 = palette_t(I)
    x2 = remove(BLACK, x1)
    x3 = identity(p_g)
    x4 = rbind(get_nth_t, F0)
    x5 = c_iz_n(S, x3, x4)
    x6 = other_f(x2, x5)
    x7 = rbind(shoot, UNITY)
    x8 = rbind(shoot, NEG_UNITY)
    x9 = fork(combine, x7, x8)
    x10 = rbind(add, UP_RIGHT)
    x11 = rbind(corner, R1)
    x12 = o_g(I, R5)
    x13 = colorfilter(x12, x5)
    x14 = lbind(index, I)
    x15 = compose(x14, x11)
    x16 = matcher(x15, x5)
    x17 = sfilter_f(x13, x16)
    x18 = apply(x11, x17)
    x19 = apply(x10, x18)
    x20 = mapply(x9, x19)
    x21 = rbind(add, DOWN_LEFT)
    x22 = rbind(corner, R2)
    x23 = difference(x13, x17)
    x24 = apply(x22, x23)
    x25 = apply(x21, x24)
    x26 = mapply(x9, x25)
    x27 = combine_f(x20, x26)
    x28 = fill(I, x6, x27)
    O = replace(x28, x5, BLACK)
    return O
