def solve_f15e1fac_one(S, I):
    return chain(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1)), branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2)), branch(equality(col_row(f_ofcolor(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I)), CYAN), R1), BLACK), identity, rbind(mir_rot_t, R0)))(fill(branch(equality(col_row(f_ofcolor(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I)), CYAN), R1), BLACK), identity, rbind(mir_rot_t, R0))(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I))), CYAN, merge(papply(shift, apply(chain(lbind(sfilter, mapply(rbind(shoot, DOWN), f_ofcolor(branch(equality(col_row(f_ofcolor(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I)), CYAN), R1), BLACK), identity, rbind(mir_rot_t, R0))(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I))), CYAN))), lbind(compose, fork(both, fork(greater, compose(rbind(get_nth_f, F0), rbind(get_nth_f, L1)), chain(decrement, rbind(get_nth_f, F0), rbind(get_nth_f, F0))), fork(greater, chain(increment, rbind(get_nth_f, L1), rbind(get_nth_f, F0)), compose(rbind(get_nth_f, F0), rbind(get_nth_f, L1))))), lbind(lbind, astuple)), pair(order(insert(BLACK, apply(rbind(get_nth_f, F0), f_ofcolor(branch(equality(col_row(f_ofcolor(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I)), CYAN), R1), BLACK), identity, rbind(mir_rot_t, R0))(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I))), RED))), identity), order(apply(decrement, insert(height_t(branch(equality(col_row(f_ofcolor(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I)), CYAN), R1), BLACK), identity, rbind(mir_rot_t, R0))(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I)))), apply(rbind(get_nth_f, F0), f_ofcolor(branch(equality(col_row(f_ofcolor(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I)), CYAN), R1), BLACK), identity, rbind(mir_rot_t, R0))(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I))), RED)))), identity))), apply(tojvec, interval(ZERO, increment(size_f(f_ofcolor(branch(equality(col_row(f_ofcolor(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I)), CYAN), R1), BLACK), identity, rbind(mir_rot_t, R0))(branch(equality(col_row(f_ofcolor(I, RED), R2), BLACK), identity, rbind(mir_rot_t, R2))(branch(portrait_f(f_ofcolor(I, RED)), identity, rbind(mir_rot_t, R1))(I))), RED))), ONE))))))


def solve_f15e1fac(S, I):
    x1 = f_ofcolor(I, RED)
    x2 = portrait_f(x1)
    x3 = rbind(mir_rot_t, R1)
    x4 = branch(x2, identity, x3)
    x5 = col_row(x1, R2)
    x6 = equality(x5, BLACK)
    x7 = rbind(mir_rot_t, R2)
    x8 = branch(x6, identity, x7)
    x9 = x4(I)
    x10 = x8(x9)
    x11 = f_ofcolor(x10, CYAN)
    x12 = col_row(x11, R1)
    x13 = equality(x12, BLACK)
    x14 = rbind(mir_rot_t, R0)
    x15 = branch(x13, identity, x14)
    x16 = chain(x4, x8, x15)
    x17 = x15(x10)
    x18 = rbind(shoot, DOWN)
    x19 = f_ofcolor(x17, CYAN)
    x20 = mapply(x18, x19)
    x21 = lbind(sfilter, x20)
    x22 = rbind(get_nth_f, F0)
    x23 = rbind(get_nth_f, L1)
    x24 = compose(x22, x23)
    x25 = chain(decrement, x22, x22)
    x26 = fork(greater, x24, x25)
    x27 = chain(increment, x23, x22)
    x28 = fork(greater, x27, x24)
    x29 = fork(both, x26, x28)
    x30 = lbind(compose, x29)
    x31 = lbind(lbind, astuple)
    x32 = chain(x21, x30, x31)
    x33 = f_ofcolor(x17, RED)
    x34 = apply(x22, x33)
    x35 = insert(BLACK, x34)
    x36 = order(x35, identity)
    x37 = height_t(x17)
    x38 = insert(x37, x34)
    x39 = apply(decrement, x38)
    x40 = order(x39, identity)
    x41 = pair(x36, x40)
    x42 = apply(x32, x41)
    x43 = size_f(x33)
    x44 = increment(x43)
    x45 = interval(ZERO, x44, ONE)
    x46 = apply(tojvec, x45)
    x47 = papply(shift, x42, x46)
    x48 = merge(x47)
    x49 = fill(x17, CYAN, x48)
    O = x16(x49)
    return O
