def solve_e179c5f4_one(S, I):
    return replace(mir_rot_t(crop(merge(repeat(crop(fill(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE, shoot(corner(f_ofcolor(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE), R1), NEG_UNITY)), corner(f_ofcolor(fill(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE, shoot(corner(f_ofcolor(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE), R1), NEG_UNITY)), BLUE), R0), astuple(decrement(height_t(subgrid(f_ofcolor(fill(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE, shoot(corner(f_ofcolor(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE), R1), NEG_UNITY)), BLUE), fill(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE, shoot(corner(f_ofcolor(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE), R1), NEG_UNITY))))), width_t(subgrid(f_ofcolor(fill(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE, shoot(corner(f_ofcolor(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE), R1), NEG_UNITY)), BLUE), fill(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE, shoot(corner(f_ofcolor(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE), R1), NEG_UNITY)))))), BURGUNDY)), ORIGIN, astuple(height_t(I), width_t(subgrid(f_ofcolor(fill(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE, shoot(corner(f_ofcolor(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE), R1), NEG_UNITY)), BLUE), fill(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE, shoot(corner(f_ofcolor(fill(I, BLUE, shoot(get_nth_f(f_ofcolor(I, BLUE), F0), UP_RIGHT)), BLUE), R1), NEG_UNITY)))))), R0), c_iz_n(S, identity(p_g), rbind(get_nth_t, F0)), c_zo_n(S, identity(p_g), rbind(get_nth_t, F0)))


def solve_e179c5f4(S, I):
    x1 = f_ofcolor(I, BLUE)
    x2 = get_nth_f(x1, F0)
    x3 = shoot(x2, UP_RIGHT)
    x4 = fill(I, BLUE, x3)
    x5 = f_ofcolor(x4, BLUE)
    x6 = corner(x5, R1)
    x7 = shoot(x6, NEG_UNITY)
    x8 = fill(x4, BLUE, x7)
    x9 = f_ofcolor(x8, BLUE)
    x10 = corner(x9, R0)
    x11 = subgrid(x9, x8)
    x12 = height_t(x11)
    x13 = decrement(x12)
    x14 = width_t(x11)
    x15 = astuple(x13, x14)
    x16 = crop(x8, x10, x15)
    x17 = repeat(x16, BURGUNDY)
    x18 = merge(x17)
    x19 = height_t(I)
    x20 = astuple(x19, x14)
    x21 = crop(x18, ORIGIN, x20)
    x22 = mir_rot_t(x21, R0)
    x23 = identity(p_g)
    x24 = rbind(get_nth_t, F0)
    x25 = c_iz_n(S, x23, x24)
    x26 = c_zo_n(S, x23, x24)
    O = replace(x22, x25, x26)
    return O
