# Generated by tokpidjin/card.py

from pile import *
from gpu_env import GPUEnv as Env
from safe_dsl import _get_safe_default
from batt_gpu import batch_process_samples_gpu

def batt(task_id, S, I, C, log_path):
    s = []
    o = []
    # Pre-mutate: t1 - differ = True - solver = False - old_items = ['identity', ' p_g'] - old_hints = ['Any', 'Any']
    try:
        t1 = identity(p_g)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t1 = _get_safe_default(identity)
    # Pre-mutate: t2 - differ = True - solver = False - old_items = ['t1', ' I'] - old_hints = None
    try:
        t2 = t1(I)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t2 = _get_safe_default(t1)
    # Pre-mutate: t3 - differ = True - solver = False - old_items = ['t1', ' C'] - old_hints = None
    try:
        t3 = t1(C)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t3 = _get_safe_default(t1)
    # Pre-mutate: t4 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t2'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    try:
        t4 = difference_tuple(t3, t2)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t4 = _get_safe_default(difference_tuple)
    # Pre-mutate: t5 - differ = True - solver = False - old_items = ['size', ' t4'] - old_hints = ['Integer', 'Container']
    try:
        t5 = size(t4)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t5 = _get_safe_default(size)
    # Pre-mutate: t6 - differ = True - solver = True - old_items = ['get_nth_t', ' t4', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    try:
        t6 = get_nth_t(t4, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t6 = _get_safe_default(get_nth_t)
    # Pre-mutate: t7 - differ = True - solver = False - old_items = ['astuple', ' t5', ' t6'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t7 = astuple(t5, t6)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t7 = _get_safe_default(astuple)
    s.append((7, 'None', 'differ_c59e6ae069a9205b311cf67a15473d64', t7))
    # Pre-mutate: t8 - differ = True - solver = False - old_items = ['rbind', ' o_g', ' R5'] - old_hints = ['Callable', 'Callable', 'Any']
    try:
        t8 = rbind(o_g, R5)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t8 = _get_safe_default(rbind)
    # Pre-mutate: t9 - differ = True - solver = False - old_items = ['t8', ' I'] - old_hints = None
    try:
        t9 = t8(I)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t9 = _get_safe_default(t8)
    # Pre-mutate: t10 - differ = True - solver = False - old_items = ['t8', ' C'] - old_hints = None
    try:
        t10 = t8(C)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t10 = _get_safe_default(t8)
    # Pre-mutate: t11 - differ = True - solver = False - old_items = ['rbind', ' sizefilter', ' ONE'] - old_hints = ['Callable', 'Callable', 'Any']
    try:
        t11 = rbind(sizefilter, ONE)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t11 = _get_safe_default(rbind)
    # Pre-mutate: t12 - differ = True - solver = False - old_items = ['t11', ' t9'] - old_hints = None
    try:
        t12 = t11(UP_RIGHT)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t12 = _get_safe_default(t11)
    # Pre-mutate: t13 - differ = True - solver = False - old_items = ['t11', ' t10'] - old_hints = None
    try:
        t13 = t11(t10)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t13 = _get_safe_default(t11)
    # Pre-mutate: t14 - differ = True - solver = False - old_items = ['difference', ' t12', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    try:
        t14 = difference(t12, t13)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t14 = _get_safe_default(difference)
    # Pre-mutate: t15 - differ = True - solver = False - old_items = ['size', ' t14'] - old_hints = ['Integer', 'Container']
    try:
        t15 = size(t14)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t15 = _get_safe_default(size)
    # Pre-mutate: t16 - differ = True - solver = True - old_items = ['get_nth_f', ' t14', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    try:
        t16 = get_nth_f(t14, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t16 = _get_safe_default(get_nth_f)
    # Pre-mutate: t17 - differ = True - solver = False - old_items = ['astuple', ' t15', ' t16'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t17 = astuple(FOUR, t16)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t17 = _get_safe_default(astuple)
    s.append((17, 'None', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t17))
    # Pre-mutate: t18 - differ = True - solver = False - old_items = ['difference', ' t13', ' t12'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    try:
        t18 = difference(t13, t12)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t18 = _get_safe_default(difference)
    # Pre-mutate: t19 - differ = True - solver = False - old_items = ['size', ' t18'] - old_hints = ['Integer', 'Container']
    try:
        t19 = size(t18)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t19 = _get_safe_default(size)
    # Pre-mutate: t20 - differ = True - solver = True - old_items = ['get_nth_f', ' t18', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    try:
        t20 = get_nth_f(t18, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t20 = _get_safe_default(get_nth_f)
    # Pre-mutate: t21 - differ = True - solver = False - old_items = ['astuple', ' t19', ' t20'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t21 = astuple(t19, t20)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t21 = _get_safe_default(astuple)
    s.append((21, 'None', 'differ_f4a4346405e974b919a4b5a52f28e40c', t21))
    # Pre-mutate: t22 - differ = True - solver = False - old_items = ['difference_tuple', ' t2', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    try:
        t22 = difference_tuple(t2, t3)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t22 = _get_safe_default(difference_tuple)
    # Pre-mutate: t23 - differ = True - solver = False - old_items = ['size', ' t22'] - old_hints = ['Integer', 'Container']
    try:
        t23 = size(t22)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t23 = _get_safe_default(size)
    # Pre-mutate: t24 - differ = True - solver = True - old_items = ['get_nth_t', ' t22', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    try:
        t24 = get_nth_t(t22, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t24 = _get_safe_default(get_nth_t)
    # Pre-mutate: t25 - differ = True - solver = False - old_items = ['astuple', ' t23', ' t24'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t25 = astuple(t23, t24)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t25 = _get_safe_default(astuple)
    s.append((25, 'None', 'differ_fc9e44c913711da609a9e25126b4b296', t25))
    # Pre-mutate: t26 - differ = False - solver = True - old_items = ['o_g_t', ' I', ' R4'] - old_hints = ['Tuple[Tuple[Tuple[int, int, int], ...], ...]', 'Grid', 'R8']
    try:
        t26 = o_g_t(I, R4)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t26 = _get_safe_default(o_g_t)
    # Pre-mutate: t27 - differ = False - solver = True - old_items = ['mir_rot_t', ' I', ' R1'] - old_hints = ['Grid', 'Grid', 'A8']
    t27 = identity(S)
    t28 = a_mr(t27)
    try:
        t29 = mir_rot_t(I, t28)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t29 = _get_safe_default(mir_rot_t)
    o.append((29, True, '74dd1130', t29))
    # Pre-mutate: t30 - differ = True - solver = False - old_items = ['t1', ' t29'] - old_hints = None
    try:
        t30 = t1(t29)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t30 = _get_safe_default(t1)
    # Pre-mutate: t31 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t30'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    try:
        t31 = difference_tuple(t3, t30)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t31 = _get_safe_default(difference_tuple)
    # Pre-mutate: t32 - differ = True - solver = False - old_items = ['size', ' t31'] - old_hints = ['Integer', 'Container']
    try:
        t32 = size(t31)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t32 = _get_safe_default(size)
    # Pre-mutate: t33 - differ = True - solver = True - old_items = ['get_nth_t', ' t31', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    try:
        t33 = get_nth_t(t31, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t33 = _get_safe_default(get_nth_t)
    # Pre-mutate: t34 - differ = True - solver = False - old_items = ['astuple', ' t32', ' t33'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t34 = astuple(t32, t33)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t34 = _get_safe_default(astuple)
    s.append((34, '74dd1130', 'differ_c59e6ae069a9205b311cf67a15473d64', t34))
    # Pre-mutate: t35 - differ = True - solver = False - old_items = ['t8', ' t29'] - old_hints = None
    try:
        t35 = t8(t29)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t35 = _get_safe_default(t8)
    # Pre-mutate: t36 - differ = True - solver = False - old_items = ['t11', ' t35'] - old_hints = None
    try:
        t36 = t11(t35)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t36 = _get_safe_default(t11)
    # Pre-mutate: t37 - differ = True - solver = False - old_items = ['difference', ' t36', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    try:
        t37 = difference(t36, t13)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t37 = _get_safe_default(difference)
    # Pre-mutate: t38 - differ = True - solver = False - old_items = ['size', ' t37'] - old_hints = ['Integer', 'Container']
    try:
        t38 = size(t37)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t38 = _get_safe_default(size)
    # Pre-mutate: t39 - differ = True - solver = True - old_items = ['get_nth_f', ' t37', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    try:
        t39 = get_nth_f(t37, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t39 = _get_safe_default(get_nth_f)
    # Pre-mutate: t40 - differ = True - solver = False - old_items = ['astuple', ' t38', ' t39'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t40 = astuple(t38, t39)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t40 = _get_safe_default(astuple)
    s.append((40, '74dd1130', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t40))
    # Pre-mutate: t41 - differ = True - solver = False - old_items = ['difference', ' t13', ' t36'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    try:
        t41 = difference(t13, t36)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t41 = _get_safe_default(difference)
    # Pre-mutate: t42 - differ = True - solver = False - old_items = ['size', ' t41'] - old_hints = ['Integer', 'Container']
    try:
        t42 = size(t41)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t42 = _get_safe_default(size)
    # Pre-mutate: t43 - differ = True - solver = True - old_items = ['get_nth_f', ' t41', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    try:
        t43 = get_nth_f(t41, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t43 = _get_safe_default(get_nth_f)
    # Pre-mutate: t44 - differ = True - solver = False - old_items = ['astuple', ' t42', ' t43'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t44 = astuple(t42, t43)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t44 = _get_safe_default(astuple)
    s.append((44, '74dd1130', 'differ_f4a4346405e974b919a4b5a52f28e40c', t44))
    # Pre-mutate: t45 - differ = True - solver = False - old_items = ['difference_tuple', ' t30', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    try:
        t45 = difference_tuple(t30, t3)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t45 = _get_safe_default(difference_tuple)
    # Pre-mutate: t46 - differ = True - solver = False - old_items = ['size', ' t45'] - old_hints = ['Integer', 'Container']
    try:
        t46 = size(t45)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t46 = _get_safe_default(size)
    # Pre-mutate: t47 - differ = True - solver = True - old_items = ['get_nth_t', ' t45', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    try:
        t47 = get_nth_t(t45, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t47 = _get_safe_default(get_nth_t)
    # Pre-mutate: t48 - differ = True - solver = False - old_items = ['astuple', ' t46', ' t47'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t48 = astuple(t46, t47)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t48 = _get_safe_default(astuple)
    s.append((48, '74dd1130', 'differ_fc9e44c913711da609a9e25126b4b296', t48))
    # Pre-mutate: t49 - differ = False - solver = True - old_items = ['colorfilter_t', ' t26', ' ZERO'] - old_hints = ['Tuple[Tuple[Tuple[int, int, int], ...], ...]', 'Tuple[Tuple[Tuple[int, int, int], ...], ...]', 'Integer']
    try:
        t49 = colorfilter_t(t26, ZERO)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t49 = _get_safe_default(colorfilter_t)
    # Pre-mutate: t50 - differ = False - solver = True - old_items = ['fork', ' equality', ' toindices', ' backdrop'] - old_hints = ['Callable', 'Callable', 'Callable', 'Callable']
    try:
        t50 = fork(equality, toindices, backdrop)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t50 = _get_safe_default(fork)
    # Pre-mutate: t51 - differ = False - solver = True - old_items = ['sfilter_f', ' t49', ' t50'] - old_hints = ['FrozenSet', 'FrozenSet', 'Callable']
    try:
        t51 = sfilter_f(t49, t50)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t51 = _get_safe_default(sfilter_f)
    # Pre-mutate: t52 - differ = False - solver = True - old_items = ['matcher', ' size', ' ZERO'] - old_hints = ['Callable', 'Callable', 'Any']
    try:
        t52 = matcher(size, ZERO)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t52 = _get_safe_default(matcher)
    # Pre-mutate: t53 - differ = False - solver = True - old_items = ['f_ofcolor', ' I', ' FIVE'] - old_hints = ['Indices', 'Grid', 'C_']
    try:
        t53 = f_ofcolor(I, GRAY)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t53 = _get_safe_default(f_ofcolor)
    # Pre-mutate: t54 - differ = False - solver = True - old_items = ['rbind', ' intersection', ' t53'] - old_hints = ['Callable', 'Callable', 'Any']
    try:
        t54 = rbind(intersection, t53)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t54 = _get_safe_default(rbind)
    # Pre-mutate: t55 - differ = False - solver = True - old_items = ['lbind', ' mapply', ' dneighbors'] - old_hints = ['Callable', 'Callable', 'Any']
    try:
        t55 = lbind(mapply, dneighbors)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t55 = _get_safe_default(lbind)
    # Pre-mutate: t56 - differ = False - solver = True - old_items = ['chain', ' t55', ' corners', ' outbox'] - old_hints = ['Callable', 'Callable', 'Callable', 'Callable']
    try:
        t56 = chain(t55, corners, outbox)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t56 = _get_safe_default(chain)
    # Pre-mutate: t57 - differ = False - solver = True - old_items = ['fork', ' difference', ' t56', ' outbox'] - old_hints = ['Callable', 'Callable', 'Callable', 'Callable']
    try:
        t57 = fork(difference, t56, outbox)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t57 = _get_safe_default(fork)
    # Pre-mutate: t58 - differ = False - solver = True - old_items = ['chain', ' t52', ' t54', ' t57'] - old_hints = ['Callable', 'Callable', 'Callable', 'Callable']
    try:
        t58 = chain(t52, t54, t57)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t58 = _get_safe_default(chain)
    # Pre-mutate: t59 - differ = False - solver = True - old_items = ['mfilter_f', ' t51', ' t58'] - old_hints = ['FrozenSet', 'FrozenSet', 'Callable']
    try:
        t59 = mfilter_f(t51, t58)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t59 = _get_safe_default(mfilter_f)
    # Pre-mutate: t60 - differ = False - solver = True - old_items = ['fill', ' I', ' FOUR', ' t59'] - old_hints = ['Grid', 'Grid', 'C_', 'Patch']
    try:
        t60 = fill(I, YELLOW, t59)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t60 = _get_safe_default(fill)
    o.append((60, True, 'e73095fd', t60))
    # Pre-mutate: t61 - differ = True - solver = False - old_items = ['t1', ' t60'] - old_hints = None
    try:
        t61 = t1(t60)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t61 = _get_safe_default(t1)
    # Pre-mutate: t62 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t61'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    try:
        t62 = difference_tuple(t3, t61)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t62 = _get_safe_default(difference_tuple)
    # Pre-mutate: t63 - differ = True - solver = False - old_items = ['size', ' t62'] - old_hints = ['Integer', 'Container']
    try:
        t63 = size(t62)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t63 = _get_safe_default(size)
    # Pre-mutate: t64 - differ = True - solver = True - old_items = ['get_nth_t', ' t62', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    try:
        t64 = get_nth_t(t62, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t64 = _get_safe_default(get_nth_t)
    # Pre-mutate: t65 - differ = True - solver = False - old_items = ['astuple', ' t63', ' t64'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t65 = astuple(t63, t64)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t65 = _get_safe_default(astuple)
    s.append((65, 'e73095fd', 'differ_c59e6ae069a9205b311cf67a15473d64', t65))
    # Pre-mutate: t66 - differ = True - solver = False - old_items = ['t8', ' t60'] - old_hints = None
    try:
        t66 = t8(t60)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t66 = _get_safe_default(t8)
    # Pre-mutate: t67 - differ = True - solver = False - old_items = ['t11', ' t66'] - old_hints = None
    try:
        t67 = t11(t66)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t67 = _get_safe_default(t11)
    # Pre-mutate: t68 - differ = True - solver = False - old_items = ['difference', ' t67', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    try:
        t68 = difference(t67, t13)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t68 = _get_safe_default(difference)
    # Pre-mutate: t69 - differ = True - solver = False - old_items = ['size', ' t68'] - old_hints = ['Integer', 'Container']
    try:
        t69 = size(t68)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t69 = _get_safe_default(size)
    # Pre-mutate: t70 - differ = True - solver = True - old_items = ['get_nth_f', ' t68', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    try:
        t70 = get_nth_f(t68, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t70 = _get_safe_default(get_nth_f)
    # Pre-mutate: t71 - differ = True - solver = False - old_items = ['astuple', ' t69', ' t70'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t71 = astuple(t69, t70)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t71 = _get_safe_default(astuple)
    s.append((71, 'e73095fd', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t71))
    # Pre-mutate: t72 - differ = True - solver = False - old_items = ['difference', ' t13', ' t67'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    try:
        t72 = difference(t13, t67)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t72 = _get_safe_default(difference)
    # Pre-mutate: t73 - differ = True - solver = False - old_items = ['size', ' t72'] - old_hints = ['Integer', 'Container']
    try:
        t73 = size(t72)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t73 = _get_safe_default(size)
    # Pre-mutate: t74 - differ = True - solver = True - old_items = ['get_nth_f', ' t72', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    try:
        t74 = get_nth_f(t72, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t74 = _get_safe_default(get_nth_f)
    # Pre-mutate: t75 - differ = True - solver = False - old_items = ['astuple', ' t73', ' t74'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t75 = astuple(t73, t74)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t75 = _get_safe_default(astuple)
    s.append((75, 'e73095fd', 'differ_f4a4346405e974b919a4b5a52f28e40c', t75))
    # Pre-mutate: t76 - differ = True - solver = False - old_items = ['difference_tuple', ' t61', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    try:
        t76 = difference_tuple(t61, t3)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t76 = _get_safe_default(difference_tuple)
    # Pre-mutate: t77 - differ = True - solver = False - old_items = ['size', ' t76'] - old_hints = ['Integer', 'Container']
    try:
        t77 = size(t76)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t77 = _get_safe_default(size)
    # Pre-mutate: t78 - differ = True - solver = True - old_items = ['get_nth_t', ' t76', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    try:
        t78 = get_nth_t(t76, F0)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t78 = _get_safe_default(get_nth_t)
    # Pre-mutate: t79 - differ = True - solver = False - old_items = ['astuple', ' t77', ' t78'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t79 = astuple(t77, t78)
    except (TypeError, AttributeError, ValueError, IndexError, KeyError):
        t79 = _get_safe_default(astuple)
    s.append((79, 'e73095fd', 'differ_fc9e44c913711da609a9e25126b4b296', t79))
    return o, s
