# Generated by tokpidjin/card.py

from pile import *
from gpu_env import GPUEnv as Env
from safe_dsl import _get_safe_default
from batt_gpu import batch_process_samples_gpu

def batt(task_id, S, I, C, log_path):
    s = []
    o = []
    # Pre-mutate: t1 - differ = True - solver = False - old_items = ['identity', ' p_g'] - old_hints = ['Any', 'Any']
    t1 = identity(p_g)
    # Pre-mutate: t2 - differ = True - solver = False - old_items = ['x1', ' I'] - old_hints = None
    t2 = x1(I)
    # Pre-mutate: t3 - differ = True - solver = False - old_items = ['x1', ' C'] - old_hints = None
    t3 = x1(C)
    # Pre-mutate: t4 - differ = True - solver = False - old_items = ['difference_tuple', ' x3', ' x2'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t4 = difference_tuple(x3, x2)
    # Pre-mutate: t5 - differ = True - solver = False - old_items = ['size', ' x4'] - old_hints = ['Integer', 'Container']
    t5 = size(x4)
    # Pre-mutate: t6 - differ = True - solver = False - old_items = ['get_nth_t', ' x4', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t6 = get_nth_t(x4, F0)
    # Pre-mutate: t7 - differ = True - solver = False - old_items = ['astuple', ' x5', ' x6'] - old_hints = ['Tuple', 'Any', 'Any']
    t7 = astuple(x5, x6)
    s.append((7, 'None', 'differ_c59e6ae069a9205b311cf67a15473d64', t7))
    # Pre-mutate: t8 - differ = True - solver = False - old_items = ['rbind', ' o_g', ' R5'] - old_hints = ['Callable', 'Callable', 'Any']
    t8 = rbind(o_g, R5)
    # Pre-mutate: t9 - differ = True - solver = False - old_items = ['rbind', ' sizefilter', ' ONE'] - old_hints = ['Callable', 'Callable', 'Any']
    t9 = rbind(sizefilter, ONE)
    # Pre-mutate: t10 - differ = True - solver = False - old_items = ['x4', ' x2'] - old_hints = None
    t10 = x4(x2)
    # Pre-mutate: t11 - differ = True - solver = False - old_items = ['x4', ' x3'] - old_hints = None
    t11 = x4(x3)
    # Pre-mutate: t12 - differ = True - solver = False - old_items = ['difference', ' x5', ' x6'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t12 = difference(x5, x6)
    # Pre-mutate: t13 - differ = True - solver = False - old_items = ['size', ' x7'] - old_hints = ['Integer', 'Container']
    t13 = size(x7)
    # Pre-mutate: t14 - differ = True - solver = False - old_items = ['get_nth_f', ' x7', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t14 = get_nth_f(x7, F0)
    # Pre-mutate: t15 - differ = True - solver = False - old_items = ['astuple', ' x8', ' x9'] - old_hints = ['Tuple', 'Any', 'Any']
    t15 = astuple(x8, x9)
    s.append((15, 'None', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t15))
    # Pre-mutate: t16 - differ = True - solver = False - old_items = ['difference', ' x6', ' x5'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t16 = difference(x6, x5)
    s.append((16, 'None', 'differ_f4a4346405e974b919a4b5a52f28e40c', t16))
    # Pre-mutate: t17 - differ = True - solver = False - old_items = ['difference_tuple', ' x2', ' x3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t17 = difference_tuple(x2, x3)
    s.append((17, 'None', 'differ_fc9e44c913711da609a9e25126b4b296', t17))
    # Pre-mutate: t18 - differ = False - solver = True - old_items = ['f_ofcolor', ' I', ' THREE'] - old_hints = ['Indices', 'Grid', 'C_']
    t18 = f_ofcolor(I, GREEN)
    # Pre-mutate: t19 - differ = False - solver = True - old_items = ['rbind', ' shoot', ' DOWN'] - old_hints = ['Callable', 'Callable', 'Any']
    t19 = rbind(shoot, DOWN)
    # Pre-mutate: t20 - differ = False - solver = True - old_items = ['mapply_t', ' neighbors', ' t18'] - old_hints = ['Tuple', 'Callable', 'Tuple']
    t20 = mapply_t(neighbors, t18)
    # Pre-mutate: t21 - differ = False - solver = True - old_items = ['compose', ' t19', ' center'] - old_hints = ['Callable', 'Callable', 'Callable']
    t21 = compose(t19, center)
    # Pre-mutate: t22 - differ = False - solver = True - old_items = ['fill', ' I', ' SIX', ' t20'] - old_hints = ['Grid', 'Grid', 'C_', 'Patch']
    t22 = fill(I, MAGENTA, t20)
    # Pre-mutate: t23 - differ = False - solver = True - old_items = ['fork', ' recolor_i', ' color', ' t21'] - old_hints = ['Callable', 'Callable', 'Callable', 'Callable']
    t23 = fork(recolor_i, color, t21)
    # Pre-mutate: t24 - differ = False - solver = True - old_items = ['f_ofcolor', ' I', ' EIGHT'] - old_hints = ['Indices', 'Grid', 'C_']
    t24 = f_ofcolor(I, CYAN)
    # Pre-mutate: t25 - differ = False - solver = True - old_items = ['o_g_t', ' I', ' R5'] - old_hints = ['Tuple[Tuple[Tuple[int, int, int], ...], ...]', 'Grid', 'R8']
    t25 = o_g_t(I, R5)
    # Pre-mutate: t26 - differ = False - solver = True - old_items = ['mapply_t', ' neighbors', ' t24'] - old_hints = ['Tuple', 'Callable', 'Tuple']
    t26 = mapply_t(neighbors, t24)
    # Pre-mutate: t27 - differ = False - solver = True - old_items = ['mapply_t', ' t23', ' t25'] - old_hints = ['Tuple', 'Callable', 'Tuple']
    t27 = mapply_t(t23, t25)
    # Pre-mutate: t28 - differ = False - solver = True - old_items = ['fill', ' t22', ' FOUR', ' t26'] - old_hints = ['Grid', 'Grid', 'C_', 'Patch']
    # GPU Batch Pattern: Sample processing (t28-t31)
    t28, t29, t30, t31 = batch_process_samples_gpu(S)
    t32 = dedupe(t30)
    t33 = dedupe(t31)
    t34 = difference_tuple(t33, t32)
    t35 = get_nth_t(t34, F2)
    t36 = fill(t22, t35, t26)
    # Pre-mutate: t37 - differ = False - solver = True - old_items = ['paint', ' I', ' t27'] - old_hints = ['Grid', 'Grid', 'Object']
    t37 = paint(I, t27)
    o.append((37, False, 'd037b0a7', t37))
    # Pre-mutate: t38 - differ = True - solver = False - old_items = ['x1', ' t37'] - old_hints = None
    t38 = x1(t37)
    s.append((38, 'd037b0a7', 'differ_c59e6ae069a9205b311cf67a15473d64', t38))
    s.append((38, 'd037b0a7', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t38))
    s.append((38, 'd037b0a7', 'differ_f4a4346405e974b919a4b5a52f28e40c', t38))
    s.append((38, 'd037b0a7', 'differ_fc9e44c913711da609a9e25126b4b296', t38))
    # Pre-mutate: t39 - differ = False - solver = True - old_items = ['f_ofcolor', ' I', ' TWO'] - old_hints = ['Indices', 'Grid', 'C_']
    t39 = f_ofcolor(I, RED)
    # Pre-mutate: t40 - differ = False - solver = True - old_items = ['mapply_t', ' neighbors', ' t39'] - old_hints = ['Tuple', 'Callable', 'Tuple']
    t40 = mapply_t(neighbors, t39)
    # Pre-mutate: t41 - differ = False - solver = True - old_items = ['fill', ' t36', ' ONE', ' t40'] - old_hints = ['Grid', 'Grid', 'C_', 'Patch']
    t41 = fill(t36, BLUE, t40)
    o.append((41, True, '913fb3ed', t41))
    # Pre-mutate: t42 - differ = True - solver = False - old_items = ['x1', ' t41'] - old_hints = None
    t42 = x1(t41)
    s.append((42, '913fb3ed', 'differ_c59e6ae069a9205b311cf67a15473d64', t42))
    s.append((42, '913fb3ed', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t42))
    s.append((42, '913fb3ed', 'differ_f4a4346405e974b919a4b5a52f28e40c', t42))
    s.append((42, '913fb3ed', 'differ_fc9e44c913711da609a9e25126b4b296', t42))
    return o, s
