# Generated by tokpidjin/card.py

from dsl import *
from safe_dsl import _get_safe_default

def batt(task_id, S, I, C, log_path):
    s = []
    o = []
    # Pre-mutate: t1 - differ = True - solver = False - old_items = ['identity', ' p_g'] - old_hints = ['Any', 'Any']
    t1 = identity(p_g)
    # Pre-mutate: t2 - differ = True - solver = False - old_items = ['t1', ' I'] - old_hints = None
    t2 = t1(I)
    # Pre-mutate: t3 - differ = True - solver = False - old_items = ['t1', ' C'] - old_hints = None
    t3 = t1(C)
    # Pre-mutate: t4 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t2'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t4 = difference_tuple(t3, t2)
    # Pre-mutate: t5 - differ = True - solver = False - old_items = ['size', ' t4'] - old_hints = ['Integer', 'Container']
    t5 = size(t4)
    # Pre-mutate: t6 - differ = True - solver = True - old_items = ['get_nth_t', ' t4', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t6 = get_nth_t(t4, F0)
    # Pre-mutate: t7 - differ = True - solver = False - old_items = ['astuple', ' t5', ' t6'] - old_hints = ['Tuple', 'Any', 'Any']
    t7 = astuple(t5, t6)
    s.append((7, 'None', 'differ_c59e6ae069a9205b311cf67a15473d64', t7))
    # Pre-mutate: t8 - differ = True - solver = False - old_items = ['rbind', ' o_g', ' R5'] - old_hints = ['Callable', 'Callable', 'Any']
    t8 = rbind(o_g, R5)
    # Pre-mutate: t9 - differ = True - solver = False - old_items = ['t8', ' I'] - old_hints = None
    t9 = t8(I)
    # Pre-mutate: t10 - differ = True - solver = False - old_items = ['t8', ' C'] - old_hints = None
    t10 = t8(C)
    # Pre-mutate: t11 - differ = True - solver = False - old_items = ['rbind', ' sizefilter', ' ONE'] - old_hints = ['Callable', 'Callable', 'Any']
    t11 = rbind(sizefilter, ONE)
    # Pre-mutate: t12 - differ = True - solver = False - old_items = ['t11', ' t9'] - old_hints = None
    t12 = t11(t9)
    # Pre-mutate: t13 - differ = True - solver = False - old_items = ['t11', ' t10'] - old_hints = None
    t13 = t11(t10)
    # Pre-mutate: t14 - differ = True - solver = False - old_items = ['difference', ' t12', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t14 = difference(t12, t13)
    # Pre-mutate: t15 - differ = True - solver = False - old_items = ['size', ' t14'] - old_hints = ['Integer', 'Container']
    t15 = size(t14)
    # Pre-mutate: t16 - differ = True - solver = True - old_items = ['get_nth_f', ' t14', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t16 = get_nth_f(t14, F0)
    # Pre-mutate: t17 - differ = True - solver = False - old_items = ['astuple', ' t15', ' t16'] - old_hints = ['Tuple', 'Any', 'Any']
    t17 = astuple(t15, t16)
    s.append((17, 'None', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t17))
    # Pre-mutate: t18 - differ = True - solver = False - old_items = ['difference', ' t13', ' t12'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t18 = difference(t13, t12)
    # Pre-mutate: t19 - differ = True - solver = False - old_items = ['size', ' t18'] - old_hints = ['Integer', 'Container']
    t19 = size(t18)
    # Pre-mutate: t20 - differ = True - solver = True - old_items = ['get_nth_f', ' t18', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t20 = get_nth_f(t18, F0)
    # Pre-mutate: t21 - differ = True - solver = False - old_items = ['astuple', ' t19', ' t20'] - old_hints = ['Tuple', 'Any', 'Any']
    t21 = astuple(t19, t20)
    s.append((21, 'None', 'differ_f4a4346405e974b919a4b5a52f28e40c', t21))
    # Pre-mutate: t22 - differ = True - solver = False - old_items = ['difference_tuple', ' t2', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t22 = difference_tuple(t2, t3)
    # Pre-mutate: t23 - differ = True - solver = False - old_items = ['size', ' t22'] - old_hints = ['Integer', 'Container']
    t23 = size(t22)
    # Pre-mutate: t24 - differ = True - solver = True - old_items = ['get_nth_t', ' t22', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t24 = get_nth_t(t22, F0)
    # Pre-mutate: t25 - differ = True - solver = False - old_items = ['astuple', ' t23', ' t24'] - old_hints = ['Tuple', 'Any', 'Any']
    t25 = astuple(t23, t24)
    s.append((25, 'None', 'differ_fc9e44c913711da609a9e25126b4b296', t25))
    # Pre-mutate: t26 - differ = False - solver = True - old_items = ['fork', ' recolor_i', ' color', ' backdrop'] - old_hints = ['Callable', 'Callable', 'Callable', 'Callable']
    t26 = fork(recolor_i, color, backdrop)
    # Pre-mutate: t27 - differ = False - solver = True - old_items = ['o_g_t', ' I', ' R7'] - old_hints = ['Tuple[Tuple[Tuple[int, int, int], ...], ...]', 'Grid', 'R8']
    t27 = o_g_t(I, R7)
    # Pre-mutate: t28 - differ = False - solver = True - old_items = ['fgpartition', ' I'] - old_hints = ['Objects', 'Grid']
    t28 = fgpartition(I)
    # Pre-mutate: t29 - differ = False - solver = True - old_items = ['get_nth_t', ' t27', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t29 = get_nth_t(t27, F0)
    # Pre-mutate: t30 - differ = False - solver = True - old_items = ['apply', ' t26', ' t28'] - old_hints = ['Container', 'Callable', 'Container']
    t30 = apply(t26, t28)
    # Pre-mutate: t31 - differ = False - solver = True - old_items = ['subgrid', ' t29', ' I'] - old_hints = ['Grid', 'Patch', 'Grid']
    t31 = subgrid(t29, I)
    o.append((31, False, '1cf80156', t31))
    # Pre-mutate: t32 - differ = True - solver = False - old_items = ['t1', ' t31'] - old_hints = None
    t32 = t1(t31)
    # Pre-mutate: t33 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t32'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t33 = difference_tuple(t3, t32)
    # Pre-mutate: t34 - differ = True - solver = False - old_items = ['size', ' t33'] - old_hints = ['Integer', 'Container']
    t34 = size(t33)
    # Pre-mutate: t35 - differ = True - solver = True - old_items = ['get_nth_t', ' t33', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t35 = get_nth_t(t33, F0)
    # Pre-mutate: t36 - differ = True - solver = False - old_items = ['astuple', ' t34', ' t35'] - old_hints = ['Tuple', 'Any', 'Any']
    t36 = astuple(t34, t35)
    s.append((36, '1cf80156', 'differ_c59e6ae069a9205b311cf67a15473d64', t36))
    # Pre-mutate: t37 - differ = True - solver = False - old_items = ['t8', ' t31'] - old_hints = None
    t37 = t8(t31)
    # Pre-mutate: t38 - differ = True - solver = False - old_items = ['t11', ' t37'] - old_hints = None
    t38 = t11(t37)
    # Pre-mutate: t39 - differ = True - solver = False - old_items = ['difference', ' t38', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t39 = difference(t38, t13)
    # Pre-mutate: t40 - differ = True - solver = False - old_items = ['size', ' t39'] - old_hints = ['Integer', 'Container']
    t40 = size(t39)
    # Pre-mutate: t41 - differ = True - solver = True - old_items = ['get_nth_f', ' t39', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t41 = get_nth_f(t39, F0)
    # Pre-mutate: t42 - differ = True - solver = False - old_items = ['astuple', ' t40', ' t41'] - old_hints = ['Tuple', 'Any', 'Any']
    t42 = astuple(t40, t41)
    s.append((42, '1cf80156', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t42))
    # Pre-mutate: t43 - differ = True - solver = False - old_items = ['difference', ' t13', ' t38'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t43 = difference(t13, t38)
    # Pre-mutate: t44 - differ = True - solver = False - old_items = ['size', ' t43'] - old_hints = ['Integer', 'Container']
    t44 = size(t43)
    # Pre-mutate: t45 - differ = True - solver = True - old_items = ['get_nth_f', ' t43', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t45 = get_nth_f(t43, F0)
    # Pre-mutate: t46 - differ = True - solver = False - old_items = ['astuple', ' t44', ' t45'] - old_hints = ['Tuple', 'Any', 'Any']
    t46 = astuple(t44, t45)
    s.append((46, '1cf80156', 'differ_f4a4346405e974b919a4b5a52f28e40c', t46))
    # Pre-mutate: t47 - differ = True - solver = False - old_items = ['difference_tuple', ' t32', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t47 = difference_tuple(t32, t3)
    # Pre-mutate: t48 - differ = True - solver = False - old_items = ['size', ' t47'] - old_hints = ['Integer', 'Container']
    t48 = size(t47)
    # Pre-mutate: t49 - differ = True - solver = True - old_items = ['get_nth_t', ' t47', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t49 = get_nth_t(t47, F0)
    # Pre-mutate: t50 - differ = True - solver = False - old_items = ['astuple', ' t48', ' t49'] - old_hints = ['Tuple', 'Any', 'Any']
    t50 = astuple(t48, t49)
    s.append((50, '1cf80156', 'differ_fc9e44c913711da609a9e25126b4b296', t50))
    # Pre-mutate: t51 - differ = False - solver = True - old_items = ['mfilter_f', ' t30', ' hline_o'] - old_hints = ['FrozenSet', 'FrozenSet', 'Callable']
    t51 = mfilter_f(t30, hline_o)
    # Pre-mutate: t52 - differ = False - solver = True - old_items = ['paint', ' I', ' t51'] - old_hints = ['Grid', 'Grid', 'Object']
    t52 = paint(I, t51)
    o.append((52, False, '22eb0ac0', t52))
    # Pre-mutate: t53 - differ = True - solver = False - old_items = ['t1', ' t52'] - old_hints = None
    t53 = t1(t52)
    # Pre-mutate: t54 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t53'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t54 = difference_tuple(t3, t53)
    # Pre-mutate: t55 - differ = True - solver = False - old_items = ['size', ' t54'] - old_hints = ['Integer', 'Container']
    t55 = size(t54)
    # Pre-mutate: t56 - differ = True - solver = True - old_items = ['get_nth_t', ' t54', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t56 = get_nth_t(t54, F0)
    # Pre-mutate: t57 - differ = True - solver = False - old_items = ['astuple', ' t55', ' t56'] - old_hints = ['Tuple', 'Any', 'Any']
    t57 = astuple(t55, t56)
    s.append((57, '22eb0ac0', 'differ_c59e6ae069a9205b311cf67a15473d64', t57))
    # Pre-mutate: t58 - differ = True - solver = False - old_items = ['t8', ' t52'] - old_hints = None
    t58 = t8(t52)
    # Pre-mutate: t59 - differ = True - solver = False - old_items = ['t11', ' t58'] - old_hints = None
    t59 = t11(t58)
    # Pre-mutate: t60 - differ = True - solver = False - old_items = ['difference', ' t59', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t60 = difference(t59, t13)
    # Pre-mutate: t61 - differ = True - solver = False - old_items = ['size', ' t60'] - old_hints = ['Integer', 'Container']
    t61 = size(t60)
    # Pre-mutate: t62 - differ = True - solver = True - old_items = ['get_nth_f', ' t60', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t62 = get_nth_f(t60, F0)
    # Pre-mutate: t63 - differ = True - solver = False - old_items = ['astuple', ' t61', ' t62'] - old_hints = ['Tuple', 'Any', 'Any']
    t63 = astuple(t61, t62)
    s.append((63, '22eb0ac0', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t63))
    # Pre-mutate: t64 - differ = True - solver = False - old_items = ['difference', ' t13', ' t59'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t64 = difference(t13, t59)
    # Pre-mutate: t65 - differ = True - solver = False - old_items = ['size', ' t64'] - old_hints = ['Integer', 'Container']
    t65 = size(t64)
    # Pre-mutate: t66 - differ = True - solver = True - old_items = ['get_nth_f', ' t64', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t66 = get_nth_f(t64, F0)
    # Pre-mutate: t67 - differ = True - solver = False - old_items = ['astuple', ' t65', ' t66'] - old_hints = ['Tuple', 'Any', 'Any']
    t67 = astuple(t65, t66)
    s.append((67, '22eb0ac0', 'differ_f4a4346405e974b919a4b5a52f28e40c', t67))
    # Pre-mutate: t68 - differ = True - solver = False - old_items = ['difference_tuple', ' t53', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t68 = difference_tuple(t53, t3)
    # Pre-mutate: t69 - differ = True - solver = False - old_items = ['size', ' t68'] - old_hints = ['Integer', 'Container']
    t69 = size(t68)
    # Pre-mutate: t70 - differ = True - solver = True - old_items = ['get_nth_t', ' t68', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t70 = get_nth_t(t68, F0)
    # Pre-mutate: t71 - differ = True - solver = False - old_items = ['astuple', ' t69', ' t70'] - old_hints = ['Tuple', 'Any', 'Any']
    t71 = astuple(t69, t70)
    s.append((71, '22eb0ac0', 'differ_fc9e44c913711da609a9e25126b4b296', t71))
    return o, s
