# Generated by tokpidjin/card.py

from pile import *
from gpu_env import GPUEnv as Env
from safe_dsl import _get_safe_default
from batt_gpu import batch_process_samples_gpu

def batt(task_id, S, I, C, log_path):
    s = []
    o = []
    # t1 - differ = True - solver = False - old_items = ['identity', ' p_g'] - old_hints = ['Any', 'Any']
        t1 = identity(p_g)
    # t2 - differ = True - solver = False - old_items = ['t1', ' I'] - old_hints = None
        t2 = t1(I)
    # t3 - differ = True - solver = False - old_items = ['t1', ' C'] - old_hints = None
        t3 = t1(C)
    # t4 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t2'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
        t4 = difference_tuple(t3, t2)
    # t5 - differ = True - solver = False - old_items = ['size', ' t4'] - old_hints = ['Integer', 'Container']
        t5 = size(t4)
    # t6 - differ = True - solver = True - old_items = ['get_nth_t', ' t4', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
        t6 = get_nth_t(t4, F0)
    # t7 - differ = True - solver = False - old_items = ['astuple', ' t5', ' t6'] - old_hints = ['Tuple', 'Any', 'Any']
        t7 = astuple(t5, t6)
    s.append((7, 'None', 'differ_c59e6ae069a9205b311cf67a15473d64', t7))
    # t8 - differ = True - solver = False - old_items = ['rbind', ' o_g', ' R5'] - old_hints = ['Callable', 'Callable', 'Any']
        t8 = rbind(o_g, R5)
    # t9 - differ = True - solver = False - old_items = ['t8', ' I'] - old_hints = None
        t9 = t8(I)
    # t10 - differ = True - solver = False - old_items = ['t8', ' C'] - old_hints = None
        t10 = t8(C)
    # t11 - differ = True - solver = False - old_items = ['rbind', ' sizefilter', ' ONE'] - old_hints = ['Callable', 'Callable', 'Any']
        t11 = rbind(sizefilter, ONE)
    # t12 - differ = True - solver = False - old_items = ['t11', ' t9'] - old_hints = None
        t12 = t11(t9)
    # t13 - differ = True - solver = False - old_items = ['t11', ' t10'] - old_hints = None
        t13 = t11(t10)
    # t14 - differ = True - solver = False - old_items = ['difference', ' t12', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
        t14 = difference(t12, t13)
    # t15 - differ = True - solver = False - old_items = ['size', ' t14'] - old_hints = ['Integer', 'Container']
        t15 = size(t14)
    # t16 - differ = True - solver = True - old_items = ['get_nth_f', ' t14', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
        t16 = get_nth_f(t14, F0)
    # t17 - differ = True - solver = False - old_items = ['astuple', ' t15', ' t16'] - old_hints = ['Tuple', 'Any', 'Any']
        t17 = astuple(t15, t16)
    s.append((17, 'None', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t17))
    # t18 - differ = True - solver = False - old_items = ['difference', ' t13', ' t12'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
        t18 = difference(t13, t12)
    # t19 - differ = True - solver = False - old_items = ['size', ' t18'] - old_hints = ['Integer', 'Container']
        t19 = size(t18)
    # t20 - differ = True - solver = True - old_items = ['get_nth_f', ' t18', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
        t20 = get_nth_f(t18, F0)
    # t21 - differ = True - solver = False - old_items = ['astuple', ' t19', ' t20'] - old_hints = ['Tuple', 'Any', 'Any']
        t21 = astuple(t19, t20)
    s.append((21, 'None', 'differ_f4a4346405e974b919a4b5a52f28e40c', t21))
    # t22 - differ = True - solver = False - old_items = ['difference_tuple', ' t2', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
        t22 = difference_tuple(t2, t3)
    # t23 - differ = True - solver = False - old_items = ['size', ' t22'] - old_hints = ['Integer', 'Container']
        t23 = size(t22)
    # t24 - differ = True - solver = True - old_items = ['get_nth_t', ' t22', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
        t24 = get_nth_t(t22, F0)
    # t25 - differ = True - solver = False - old_items = ['astuple', ' t23', ' t24'] - old_hints = ['Tuple', 'Any', 'Any']
        t25 = astuple(t23, t24)
    s.append((25, 'None', 'differ_fc9e44c913711da609a9e25126b4b296', t25))
    # t26 - differ = False - solver = True - old_items = ['rbind', ' get_rank', ' F0'] - old_hints = ['Callable', 'Callable', 'Any']
        t26 = rbind(get_rank, F0)
    # t27 - differ = False - solver = True - old_items = ['lbind', ' apply', ' t26'] - old_hints = ['Callable', 'Callable', 'Any']
        t27 = lbind(apply, t26)
    # t28 - differ = False - solver = True - old_items = ['replace', ' I', ' FOUR', ' ZERO'] - old_hints = ['Grid', 'Grid', 'C_', 'C_']
        t28 = replace(I, FOUR, BLACK)
    # t29 - differ = False - solver = True - old_items = ['mir_rot_t', ' t28', ' R1'] - old_hints = ['Grid', 'Grid', 'A8']
        t29 = mir_rot_t(t28, R1)
    # t30 - differ = False - solver = True - old_items = ['papply', ' pair', ' t28', ' t29'] - old_hints = ['Tuple', 'Callable', 'Tuple', 'Tuple']
        t30 = papply(pair, t28, t29)
    # t31 - differ = False - solver = True - old_items = ['apply', ' t27', ' t30'] - old_hints = ['Container', 'Callable', 'Container']
        t31 = apply(t27, t30)
    # t32 - differ = False - solver = True - old_items = ['mir_rot_t', ' t31', ' R3'] - old_hints = ['Grid', 'Grid', 'A8']
        t32 = mir_rot_t(t31, R3)
    # t33 - differ = False - solver = True - old_items = ['papply', ' pair', ' t31', ' t32'] - old_hints = ['Tuple', 'Callable', 'Tuple', 'Tuple']
        t33 = papply(pair, t31, t32)
    # t34 - differ = False - solver = True - old_items = ['apply', ' t27', ' t33'] - old_hints = ['Container', 'Callable', 'Container']
        t34 = apply(t27, t33)
    # t35 - differ = False - solver = True - old_items = ['mir_rot_t', ' t34', ' R3'] - old_hints = ['Grid', 'Grid', 'A8']
        t35 = mir_rot_t(t34, R3)
    o.append((35, False, 'b8825c91', t35))
    # t36 - differ = True - solver = False - old_items = ['t1', ' t35'] - old_hints = None
        t36 = t1(t35)
    # t37 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t36'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
        t37 = difference_tuple(t3, t36)
    # t38 - differ = True - solver = False - old_items = ['size', ' t37'] - old_hints = ['Integer', 'Container']
        t38 = size(t37)
    # t39 - differ = True - solver = True - old_items = ['get_nth_t', ' t37', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
        t39 = get_nth_t(t37, F0)
    # t40 - differ = True - solver = False - old_items = ['astuple', ' t38', ' t39'] - old_hints = ['Tuple', 'Any', 'Any']
        t40 = astuple(t38, t39)
    s.append((40, 'b8825c91', 'differ_c59e6ae069a9205b311cf67a15473d64', t40))
    # t41 - differ = True - solver = False - old_items = ['t8', ' t35'] - old_hints = None
        t41 = t8(t35)
    # t42 - differ = True - solver = False - old_items = ['t11', ' t41'] - old_hints = None
        t42 = t11(t41)
    # t43 - differ = True - solver = False - old_items = ['difference', ' t42', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
        t43 = difference(t42, t13)
    # t44 - differ = True - solver = False - old_items = ['size', ' t43'] - old_hints = ['Integer', 'Container']
        t44 = size(t43)
    # t45 - differ = True - solver = True - old_items = ['get_nth_f', ' t43', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
        t45 = get_nth_f(t43, F0)
    # t46 - differ = True - solver = False - old_items = ['astuple', ' t44', ' t45'] - old_hints = ['Tuple', 'Any', 'Any']
        t46 = astuple(t44, t45)
    s.append((46, 'b8825c91', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t46))
    # t47 - differ = True - solver = False - old_items = ['difference', ' t13', ' t42'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
        t47 = difference(t13, t42)
    # t48 - differ = True - solver = False - old_items = ['size', ' t47'] - old_hints = ['Integer', 'Container']
        t48 = size(t47)
    # t49 - differ = True - solver = True - old_items = ['get_nth_f', ' t47', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
        t49 = get_nth_f(t47, F0)
    # t50 - differ = True - solver = False - old_items = ['astuple', ' t48', ' t49'] - old_hints = ['Tuple', 'Any', 'Any']
        t50 = astuple(t48, t49)
    s.append((50, 'b8825c91', 'differ_f4a4346405e974b919a4b5a52f28e40c', t50))
    # t51 - differ = True - solver = False - old_items = ['difference_tuple', ' t36', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
        t51 = difference_tuple(t36, t3)
    # t52 - differ = True - solver = False - old_items = ['size', ' t51'] - old_hints = ['Integer', 'Container']
        t52 = size(t51)
    # t53 - differ = True - solver = True - old_items = ['get_nth_t', ' t51', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
        t53 = get_nth_t(t51, F0)
    # t54 - differ = True - solver = False - old_items = ['astuple', ' t52', ' t53'] - old_hints = ['Tuple', 'Any', 'Any']
        t54 = astuple(t52, t53)
    s.append((54, 'b8825c91', 'differ_fc9e44c913711da609a9e25126b4b296', t54))
    return o, s
