def solve_b775ac94_one(S, I):
    return paint(paint(paint(I, mapply(fork(recolor_o, chain(lbind(index, I), rbind(get_nth_f, F0), fork(intersection, lbind(compose, toindices)(fork(combine, fork(insert, fork(extract, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), chain(rbind(compose, initset), lbind(rbind, adjacent), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))), chain(lbind(recolor_i, ZERO), delta, fork(insert, fork(extract, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), chain(rbind(compose, initset), lbind(rbind, adjacent), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))))), lbind(compose, toindices)(fork(shift, lbind(compose, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))(fork(shift, rbind(mir_rot_f, R0), fork(multiply, shape_f, chain(toivec, rbind(get_nth_f, F0), fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))))))), lbind(compose, compose(crement, invert))(chain(toivec, rbind(get_nth_f, F0), fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))))))))), fork(shift, lbind(compose, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))(fork(shift, rbind(mir_rot_f, R0), fork(multiply, shape_f, chain(toivec, rbind(get_nth_f, F0), fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))))))), lbind(compose, compose(crement, invert))(chain(toivec, rbind(get_nth_f, F0), fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))))))), o_g(I, R3))), mapply(fork(recolor_o, chain(lbind(index, I), rbind(get_nth_f, F0), fork(intersection, lbind(compose, toindices)(fork(combine, fork(insert, fork(extract, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), chain(rbind(compose, initset), lbind(rbind, adjacent), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))), chain(lbind(recolor_i, ZERO), delta, fork(insert, fork(extract, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), chain(rbind(compose, initset), lbind(rbind, adjacent), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))))), lbind(compose, toindices)(fork(shift, lbind(compose, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))(fork(shift, rbind(mir_rot_f, R2), fork(multiply, shape_f, chain(tojvec, rbind(get_nth_f, L1), fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))))))), lbind(compose, compose(crement, invert))(chain(tojvec, rbind(get_nth_f, L1), fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))))))))), fork(shift, lbind(compose, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))(fork(shift, rbind(mir_rot_f, R2), fork(multiply, shape_f, chain(tojvec, rbind(get_nth_f, L1), fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))))))), lbind(compose, compose(crement, invert))(chain(tojvec, rbind(get_nth_f, L1), fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))))))), o_g(I, R3))), mapply(fork(recolor_o, chain(lbind(index, I), rbind(get_nth_f, F0), fork(intersection, lbind(compose, toindices)(fork(combine, fork(insert, fork(extract, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), chain(rbind(compose, initset), lbind(rbind, adjacent), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))), chain(lbind(recolor_i, ZERO), delta, fork(insert, fork(extract, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), chain(rbind(compose, initset), lbind(rbind, adjacent), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))))), lbind(compose, toindices)(fork(shift, lbind(compose, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))(fork(shift, compose(rbind(mir_rot_f, R0), rbind(mir_rot_f, R2)), fork(multiply, shape_f, fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))))), lbind(compose, compose(crement, invert))(fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))))))), fork(shift, lbind(compose, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))))(fork(shift, compose(rbind(mir_rot_f, R0), rbind(mir_rot_f, R2)), fork(multiply, shape_f, fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))))), lbind(compose, compose(crement, invert))(fork(position, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0))), fork(difference, identity, fork(sfilter, identity, chain(rbind(compose, rbind(get_nth_f, F0)), lbind(rbind, equality), rbind(get_color_rank_f, F0)))))))), o_g(I, R3)))


def solve_b775ac94(S, I):
    x1 = lbind(index, I)
    x2 = rbind(get_nth_f, F0)
    x3 = lbind(compose, toindices)
    x4 = rbind(compose, x2)
    x5 = lbind(rbind, equality)
    x6 = rbind(get_color_rank_f, F0)
    x7 = chain(x4, x5, x6)
    x8 = fork(sfilter, identity, x7)
    x9 = rbind(compose, initset)
    x10 = lbind(rbind, adjacent)
    x11 = fork(difference, identity, x8)
    x12 = chain(x9, x10, x11)
    x13 = fork(extract, x8, x12)
    x14 = fork(insert, x13, x11)
    x15 = lbind(recolor_i, ZERO)
    x16 = chain(x15, delta, x14)
    x17 = fork(combine, x14, x16)
    x18 = x3(x17)
    x19 = lbind(compose, x8)
    x20 = rbind(mir_rot_f, R0)
    x21 = fork(position, x8, x11)
    x22 = chain(toivec, x2, x21)
    x23 = fork(multiply, shape_f, x22)
    x24 = fork(shift, x20, x23)
    x25 = x19(x24)
    x26 = compose(crement, invert)
    x27 = lbind(compose, x26)
    x28 = x27(x22)
    x29 = fork(shift, x25, x28)
    x30 = x3(x29)
    x31 = fork(intersection, x18, x30)
    x32 = chain(x1, x2, x31)
    x33 = fork(recolor_o, x32, x29)
    x34 = o_g(I, R3)
    x35 = mapply(x33, x34)
    x36 = paint(I, x35)
    x37 = rbind(mir_rot_f, R2)
    x38 = rbind(get_nth_f, L1)
    x39 = chain(tojvec, x38, x21)
    x40 = fork(multiply, shape_f, x39)
    x41 = fork(shift, x37, x40)
    x42 = x19(x41)
    x43 = x27(x39)
    x44 = fork(shift, x42, x43)
    x45 = x3(x44)
    x46 = fork(intersection, x18, x45)
    x47 = chain(x1, x2, x46)
    x48 = fork(recolor_o, x47, x44)
    x49 = mapply(x48, x34)
    x50 = paint(x36, x49)
    x51 = compose(x20, x37)
    x52 = fork(multiply, shape_f, x21)
    x53 = fork(shift, x51, x52)
    x54 = x19(x53)
    x55 = x27(x21)
    x56 = fork(shift, x54, x55)
    x57 = x3(x56)
    x58 = fork(intersection, x18, x57)
    x59 = chain(x1, x2, x58)
    x60 = fork(recolor_o, x59, x56)
    x61 = mapply(x60, x34)
    O = paint(x50, x61)
    return O
