def solve_0e206a2e_one(S, I):
    return cover(paint(I, mapply(fork(mapply, compose(lbind(lbind, shift), normalize), fork(apply, chain(compose(lbind(rbind, subtract), rbind(corner, R0)), rbind(sfilter, compose(rbind(contained, remove(get_arg_rank_f(remove(ZERO, palette_t(I)), lbind(colorcount_t, I), F0), remove(ZERO, palette_t(I)))), rbind(get_nth_f, F0))), normalize), chain(lbind(occurrences, I), rbind(sfilter, compose(rbind(contained, remove(get_arg_rank_f(remove(ZERO, palette_t(I)), lbind(colorcount_t, I), F0), remove(ZERO, palette_t(I)))), rbind(get_nth_f, F0))), normalize))), mapply(lbind(rapply, combine(combine(astuple(rbind(mir_rot_f, R3), rbind(mir_rot_f, R1)), astuple(rbind(mir_rot_f, R0), rbind(mir_rot_f, R2))), totuple(apply(fork(compose, rbind(get_nth_f, F0), rbind(get_nth_f, L1)), product(combine(astuple(rbind(mir_rot_f, R3), rbind(mir_rot_f, R1)), astuple(rbind(mir_rot_f, R0), rbind(mir_rot_f, R2))), combine(astuple(rbind(mir_rot_f, R3), rbind(mir_rot_f, R1)), astuple(rbind(mir_rot_f, R0), rbind(mir_rot_f, R2)))))))), sfilter(o_g(I, R1), compose(rbind(greater, ONE), numcolors_f))))), merge_f(sfilter(o_g(I, R1), compose(rbind(greater, ONE), numcolors_f))))


def solve_0e206a2e(S, I):
    x1 = lbind(lbind, shift)
    x2 = compose(x1, normalize)
    x3 = lbind(rbind, subtract)
    x4 = rbind(corner, R0)
    x5 = compose(x3, x4)
    x6 = palette_t(I)
    x7 = remove(ZERO, x6)
    x8 = lbind(colorcount_t, I)
    x9 = get_arg_rank_f(x7, x8, F0)
    x10 = remove(x9, x7)
    x11 = rbind(contained, x10)
    x12 = rbind(get_nth_f, F0)
    x13 = compose(x11, x12)
    x14 = rbind(sfilter, x13)
    x15 = chain(x5, x14, normalize)
    x16 = lbind(occurrences, I)
    x17 = chain(x16, x14, normalize)
    x18 = fork(apply, x15, x17)
    x19 = fork(mapply, x2, x18)
    x20 = rbind(mir_rot_f, R3)
    x21 = rbind(mir_rot_f, R1)
    x22 = astuple(x20, x21)
    x23 = rbind(mir_rot_f, R0)
    x24 = rbind(mir_rot_f, R2)
    x25 = astuple(x23, x24)
    x26 = combine(x22, x25)
    x27 = rbind(get_nth_f, L1)
    x28 = fork(compose, x12, x27)
    x29 = product(x26, x26)
    x30 = apply(x28, x29)
    x31 = totuple(x30)
    x32 = combine(x26, x31)
    x33 = lbind(rapply, x32)
    x34 = o_g(I, R1)
    x35 = rbind(greater, ONE)
    x36 = compose(x35, numcolors_f)
    x37 = sfilter(x34, x36)
    x38 = mapply(x33, x37)
    x39 = mapply(x19, x38)
    x40 = paint(I, x39)
    x41 = merge_f(x37)
    O = cover(x40, x41)
    return O
