def solve_6855a6e4_one(S, I):
    return branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), paint(paint(cover(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), merge_f(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE))), shift(recolor_i(FIVE, f_ofcolor(mir_rot_t(subgrid(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1))), branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4))), R0), FIVE)), add(corner(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1))), R0), toivec(add(THREE, height_f(recolor_i(FIVE, f_ofcolor(mir_rot_t(subgrid(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1))), branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4))), R0), FIVE)))))))), shift(recolor_i(FIVE, f_ofcolor(mir_rot_t(subgrid(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), compose(flip, matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1)))), branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4))), R0), FIVE)), subtract(corner(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), compose(flip, matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1)))), R0), toivec(add(THREE, height_f(recolor_i(FIVE, f_ofcolor(mir_rot_t(subgrid(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), compose(flip, matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1)))), branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4))), R0), FIVE)))))))), mir_rot_t(paint(paint(cover(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), merge_f(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE))), shift(recolor_i(FIVE, f_ofcolor(mir_rot_t(subgrid(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1))), branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4))), R0), FIVE)), add(corner(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1))), R0), toivec(add(THREE, height_f(recolor_i(FIVE, f_ofcolor(mir_rot_t(subgrid(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1))), branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4))), R0), FIVE)))))))), shift(recolor_i(FIVE, f_ofcolor(mir_rot_t(subgrid(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), compose(flip, matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1)))), branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4))), R0), FIVE)), subtract(corner(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), compose(flip, matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1)))), R0), toivec(add(THREE, height_f(recolor_i(FIVE, f_ofcolor(mir_rot_t(subgrid(extract(colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE), compose(flip, matcher(compose(rbind(get_nth_f, F0), center), get_val_rank_f(apply(center, colorfilter(o_g(branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4)), R5), FIVE)), rbind(get_nth_f, F0), L1)))), branch(portrait_f(get_nth_f(colorfilter(fgpartition(I), TWO), F0)), I, mir_rot_t(I, R4))), R0), FIVE)))))))), R6))


def solve_6855a6e4(S, I):
    x1 = fgpartition(I)
    x2 = colorfilter(x1, TWO)
    x3 = get_nth_f(x2, F0)
    x4 = portrait_f(x3)
    x5 = mir_rot_t(I, R4)
    x6 = branch(x4, I, x5)
    x7 = o_g(x6, R5)
    x8 = colorfilter(x7, FIVE)
    x9 = merge_f(x8)
    x10 = cover(x6, x9)
    x11 = rbind(get_nth_f, F0)
    x12 = compose(x11, center)
    x13 = apply(center, x8)
    x14 = get_val_rank_f(x13, x11, L1)
    x15 = matcher(x12, x14)
    x16 = extract(x8, x15)
    x17 = subgrid(x16, x6)
    x18 = mir_rot_t(x17, R0)
    x19 = f_ofcolor(x18, FIVE)
    x20 = recolor_i(FIVE, x19)
    x21 = corner(x16, R0)
    x22 = height_f(x20)
    x23 = add(THREE, x22)
    x24 = toivec(x23)
    x25 = add(x21, x24)
    x26 = shift(x20, x25)
    x27 = paint(x10, x26)
    x28 = compose(flip, x15)
    x29 = extract(x8, x28)
    x30 = subgrid(x29, x6)
    x31 = mir_rot_t(x30, R0)
    x32 = f_ofcolor(x31, FIVE)
    x33 = recolor_i(FIVE, x32)
    x34 = corner(x29, R0)
    x35 = height_f(x33)
    x36 = add(THREE, x35)
    x37 = toivec(x36)
    x38 = subtract(x34, x37)
    x39 = shift(x33, x38)
    x40 = paint(x27, x39)
    x41 = mir_rot_t(x40, R6)
    O = branch(x4, x40, x41)
    return O
