def solve_9d9215db_one(S, I):
    return apply(lbind(apply, rbind(get_rank, F0)), papply(pair, apply(lbind(apply, rbind(get_rank, F0)), papply(pair, apply(lbind(apply, rbind(get_rank, F0)), papply(pair, paint(cover(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2))), combine_f(apply(rbind(corner, R2), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR)), apply(rbind(corner, R3), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR)))), mapply(fork(recolor_i, color, fork(shift, chain(normalize, rbind(sfilter, compose(even, rbind(get_nth_f, L1))), fork(connect, compose(rbind(add, ZERO_BY_TWO), rbind(corner, R0)), compose(rbind(add, tojvec(NEG_TWO)), rbind(corner, R1)))), compose(rbind(add, ZERO_BY_TWO), rbind(corner, R0)))), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR))), mir_rot_t(paint(cover(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2))), combine_f(apply(rbind(corner, R2), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR)), apply(rbind(corner, R3), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR)))), mapply(fork(recolor_i, color, fork(shift, chain(normalize, rbind(sfilter, compose(even, rbind(get_nth_f, L1))), fork(connect, compose(rbind(add, ZERO_BY_TWO), rbind(corner, R0)), compose(rbind(add, tojvec(NEG_TWO)), rbind(corner, R1)))), compose(rbind(add, ZERO_BY_TWO), rbind(corner, R0)))), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR))), R4))), mir_rot_t(paint(cover(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2))), combine_f(apply(rbind(corner, R2), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR)), apply(rbind(corner, R3), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR)))), mapply(fork(recolor_i, color, fork(shift, chain(normalize, rbind(sfilter, compose(even, rbind(get_nth_f, L1))), fork(connect, compose(rbind(add, ZERO_BY_TWO), rbind(corner, R0)), compose(rbind(add, tojvec(NEG_TWO)), rbind(corner, R1)))), compose(rbind(add, ZERO_BY_TWO), rbind(corner, R0)))), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR))), R5))), mir_rot_t(paint(cover(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2))), combine_f(apply(rbind(corner, R2), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR)), apply(rbind(corner, R3), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR)))), mapply(fork(recolor_i, color, fork(shift, chain(normalize, rbind(sfilter, compose(even, rbind(get_nth_f, L1))), fork(connect, compose(rbind(add, ZERO_BY_TWO), rbind(corner, R0)), compose(rbind(add, tojvec(NEG_TWO)), rbind(corner, R1)))), compose(rbind(add, ZERO_BY_TWO), rbind(corner, R0)))), sizefilter(partition(apply(lbind(apply, rbind(get_rank, F0)), papply(pair, get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), mir_rot_t(get_arg_rank_f(insert(mir_rot_t(I, R6), insert(mir_rot_t(I, R5), insert(mir_rot_t(I, R4), initset(I)))), chain(numcolors_t, lefthalf, tophalf), F0), R2)))), FOUR))), R6)))


def solve_9d9215db(S, I):
    x1 = rbind(get_rank, F0)
    x2 = lbind(apply, x1)
    x3 = mir_rot_t(I, R6)
    x4 = mir_rot_t(I, R5)
    x5 = mir_rot_t(I, R4)
    x6 = initset(I)
    x7 = insert(x5, x6)
    x8 = insert(x4, x7)
    x9 = insert(x3, x8)
    x10 = chain(numcolors_t, lefthalf, tophalf)
    x11 = get_arg_rank_f(x9, x10, F0)
    x12 = mir_rot_t(x11, R2)
    x13 = papply(pair, x11, x12)
    x14 = apply(x2, x13)
    x15 = rbind(corner, R2)
    x16 = partition(x14)
    x17 = sizefilter(x16, FOUR)
    x18 = apply(x15, x17)
    x19 = rbind(corner, R3)
    x20 = apply(x19, x17)
    x21 = combine_f(x18, x20)
    x22 = cover(x14, x21)
    x23 = rbind(get_nth_f, L1)
    x24 = compose(even, x23)
    x25 = rbind(sfilter, x24)
    x26 = rbind(add, ZERO_BY_TWO)
    x27 = rbind(corner, R0)
    x28 = compose(x26, x27)
    x29 = tojvec(NEG_TWO)
    x30 = rbind(add, x29)
    x31 = rbind(corner, R1)
    x32 = compose(x30, x31)
    x33 = fork(connect, x28, x32)
    x34 = chain(normalize, x25, x33)
    x35 = fork(shift, x34, x28)
    x36 = fork(recolor_i, color, x35)
    x37 = mapply(x36, x17)
    x38 = paint(x22, x37)
    x39 = mir_rot_t(x38, R4)
    x40 = papply(pair, x38, x39)
    x41 = apply(x2, x40)
    x42 = mir_rot_t(x38, R5)
    x43 = papply(pair, x41, x42)
    x44 = apply(x2, x43)
    x45 = mir_rot_t(x38, R6)
    x46 = papply(pair, x44, x45)
    O = apply(x2, x46)
    return O
