def solve_a78176bb_one(S, I):
    return replace(fill(I, other_f(remove(ZERO, palette_t(I)), FIVE), combine_f(mapply(fork(combine, rbind(shoot, UNITY), rbind(shoot, NEG_UNITY)), apply(rbind(add, UP_RIGHT), apply(rbind(corner, R1), sfilter_f(colorfilter(o_g(I, R5), FIVE), matcher(compose(lbind(index, I), rbind(corner, R1)), FIVE))))), mapply(fork(combine, rbind(shoot, UNITY), rbind(shoot, NEG_UNITY)), apply(rbind(add, DOWN_LEFT), apply(rbind(corner, R2), difference(colorfilter(o_g(I, R5), FIVE), sfilter_f(colorfilter(o_g(I, R5), FIVE), matcher(compose(lbind(index, I), rbind(corner, R1)), FIVE)))))))), FIVE, ZERO)


def solve_a78176bb(S, I):
    x1 = palette_t(I)
    x2 = remove(ZERO, x1)
    x3 = other_f(x2, FIVE)
    x4 = rbind(shoot, UNITY)
    x5 = rbind(shoot, NEG_UNITY)
    x6 = fork(combine, x4, x5)
    x7 = rbind(add, UP_RIGHT)
    x8 = rbind(corner, R1)
    x9 = o_g(I, R5)
    x10 = colorfilter(x9, FIVE)
    x11 = lbind(index, I)
    x12 = compose(x11, x8)
    x13 = matcher(x12, FIVE)
    x14 = sfilter_f(x10, x13)
    x15 = apply(x8, x14)
    x16 = apply(x7, x15)
    x17 = mapply(x6, x16)
    x18 = rbind(add, DOWN_LEFT)
    x19 = rbind(corner, R2)
    x20 = difference(x10, x14)
    x21 = apply(x19, x20)
    x22 = apply(x18, x21)
    x23 = mapply(x6, x22)
    x24 = combine_f(x17, x23)
    x25 = fill(I, x3, x24)
    O = replace(x25, FIVE, ZERO)
    return O
