def solve_6a1e5592_one(S, I):
    return fill(cover(I, merge_f(colorfilter(o_g(I, R5), FIVE))), ONE, mapply(chain(rbind(rbind(get_arg_rank, F0), fork(subtract, fork(subtract, fork(subtract, fork(add, chain(rbind(multiply, TEN), size, rbind(intersection, asindices(crop(I, ORIGIN, astuple(FIVE, width_t(I)))))), compose(invert, chain(rbind(multiply, TEN), size, rbind(intersection, f_ofcolor(crop(I, ORIGIN, astuple(FIVE, width_t(I))), TWO))))), chain(size, rbind(intersection, f_ofcolor(crop(I, ORIGIN, astuple(FIVE, width_t(I))), ZERO)), outbox)), compose(rbind(multiply, FIVE), rbind(col_row, R1))), chain(size, rbind(intersection, f_ofcolor(crop(I, ORIGIN, astuple(FIVE, width_t(I))), ZERO)), delta))), rbind(apply, asindices(crop(I, ORIGIN, astuple(FIVE, width_t(I))))), lbind(lbind, shift)), apply(compose(toindices, normalize), colorfilter(o_g(I, R5), FIVE))))


def solve_6a1e5592(S, I):
    x1 = o_g(I, R5)
    x2 = colorfilter(x1, FIVE)
    x3 = merge_f(x2)
    x4 = cover(I, x3)
    x5 = rbind(get_arg_rank, F0)
    x6 = rbind(multiply, TEN)
    x7 = width_t(I)
    x8 = astuple(FIVE, x7)
    x9 = crop(I, ORIGIN, x8)
    x10 = asindices(x9)
    x11 = rbind(intersection, x10)
    x12 = chain(x6, size, x11)
    x13 = f_ofcolor(x9, TWO)
    x14 = rbind(intersection, x13)
    x15 = chain(x6, size, x14)
    x16 = compose(invert, x15)
    x17 = fork(add, x12, x16)
    x18 = f_ofcolor(x9, ZERO)
    x19 = rbind(intersection, x18)
    x20 = chain(size, x19, outbox)
    x21 = fork(subtract, x17, x20)
    x22 = rbind(multiply, FIVE)
    x23 = rbind(col_row, R1)
    x24 = compose(x22, x23)
    x25 = fork(subtract, x21, x24)
    x26 = chain(size, x19, delta)
    x27 = fork(subtract, x25, x26)
    x28 = rbind(x5, x27)
    x29 = rbind(apply, x10)
    x30 = lbind(lbind, shift)
    x31 = chain(x28, x29, x30)
    x32 = compose(toindices, normalize)
    x33 = apply(x32, x2)
    x34 = mapply(x31, x33)
    O = fill(x4, ONE, x34)
    return O
