def solve_264363fd_one(S, I):
    return fill(paint(paint(cover(I, get_arg_rank_f(o_g(I, R1), size, L1)), mapply(fork(shift, compose(asobject, fork(paint, rbind(subgrid, cover(I, get_arg_rank_f(o_g(I, R1), size, L1))), compose(lbind(recolor_i, index(I, add(branch(equality(height_f(get_arg_rank_f(o_g(I, R1), size, L1)), FIVE), UP, RIGHT), center(get_arg_rank_f(o_g(I, R1), size, L1))))), fork(combine, branch(equality(height_f(get_arg_rank_f(o_g(I, R1), size, L1)), FIVE), compose(lbind(mapply, vfrontier), compose(rbind(occurrences, initset(astuple(index(I, center(get_arg_rank_f(o_g(I, R1), size, L1))), ORIGIN))), rbind(subgrid, cover(I, get_arg_rank_f(o_g(I, R1), size, L1))))), compose(lbind(mapply, hfrontier), compose(rbind(occurrences, initset(astuple(index(I, center(get_arg_rank_f(o_g(I, R1), size, L1))), ORIGIN))), rbind(subgrid, cover(I, get_arg_rank_f(o_g(I, R1), size, L1)))))), branch(equality(width_f(get_arg_rank_f(o_g(I, R1), size, L1)), FIVE), compose(lbind(mapply, hfrontier), compose(rbind(occurrences, initset(astuple(index(I, center(get_arg_rank_f(o_g(I, R1), size, L1))), ORIGIN))), rbind(subgrid, cover(I, get_arg_rank_f(o_g(I, R1), size, L1))))), compose(lbind(mapply, vfrontier), compose(rbind(occurrences, initset(astuple(index(I, center(get_arg_rank_f(o_g(I, R1), size, L1))), ORIGIN))), rbind(subgrid, cover(I, get_arg_rank_f(o_g(I, R1), size, L1)))))))))), rbind(corner, R0)), o_g(cover(I, get_arg_rank_f(o_g(I, R1), size, L1)), R1))), mapply(lbind(shift, shift(normalize(get_arg_rank_f(o_g(I, R1), size, L1)), invert(add(UNITY, astuple(equality(height_f(get_arg_rank_f(o_g(I, R1), size, L1)), FIVE), equality(width_f(get_arg_rank_f(o_g(I, R1), size, L1)), FIVE)))))), occurrences(cover(I, get_arg_rank_f(o_g(I, R1), size, L1)), initset(astuple(index(I, center(get_arg_rank_f(o_g(I, R1), size, L1))), ORIGIN))))), get_color_rank_t(cover(I, get_arg_rank_f(o_g(I, R1), size, L1)), F0), f_ofcolor(cover(I, get_arg_rank_f(o_g(I, R1), size, L1)), get_color_rank_t(cover(I, get_arg_rank_f(o_g(I, R1), size, L1)), F0)))


def solve_264363fd(S, I):
    x1 = o_g(I, R1)
    x2 = get_arg_rank_f(x1, size, L1)
    x3 = cover(I, x2)
    x4 = rbind(subgrid, x3)
    x5 = height_f(x2)
    x6 = equality(x5, FIVE)
    x7 = branch(x6, UP, RIGHT)
    x8 = center(x2)
    x9 = add(x7, x8)
    x10 = index(I, x9)
    x11 = lbind(recolor_i, x10)
    x12 = lbind(mapply, vfrontier)
    x13 = index(I, x8)
    x14 = astuple(x13, ORIGIN)
    x15 = initset(x14)
    x16 = rbind(occurrences, x15)
    x17 = compose(x16, x4)
    x18 = compose(x12, x17)
    x19 = lbind(mapply, hfrontier)
    x20 = compose(x19, x17)
    x21 = branch(x6, x18, x20)
    x22 = width_f(x2)
    x23 = equality(x22, FIVE)
    x24 = branch(x23, x20, x18)
    x25 = fork(combine, x21, x24)
    x26 = compose(x11, x25)
    x27 = fork(paint, x4, x26)
    x28 = compose(asobject, x27)
    x29 = rbind(corner, R0)
    x30 = fork(shift, x28, x29)
    x31 = o_g(x3, R1)
    x32 = mapply(x30, x31)
    x33 = paint(x3, x32)
    x34 = normalize(x2)
    x35 = astuple(x6, x23)
    x36 = add(UNITY, x35)
    x37 = invert(x36)
    x38 = shift(x34, x37)
    x39 = lbind(shift, x38)
    x40 = occurrences(x3, x15)
    x41 = mapply(x39, x40)
    x42 = paint(x33, x41)
    x43 = get_color_rank_t(x3, F0)
    x44 = f_ofcolor(x3, x43)
    O = fill(x42, x43, x44)
    return O
