def solve_39e1d7f9_one(S, I):
    return paint(I, mapply(lbind(shift, asobject(crop(I, decrement(subtract(corner(get_arg_rank_f(colorfilter(o_g(I, R5), color(get_nth_t(remove_f(get_nth_t(order(fgpartition(I), height_f), L1), order(fgpartition(I), height_f)), L1))), chain(chain(size, lbind(remove, get_color_rank_t(I, F0)), palette_t), rbind(toobject, I), power(outbox, TWO)), F0), R0), shape_f(get_arg_rank_f(colorfilter(o_g(I, R5), color(get_nth_t(remove_f(get_nth_t(order(fgpartition(I), height_f), L1), order(fgpartition(I), height_f)), L1))), chain(chain(size, lbind(remove, get_color_rank_t(I, F0)), palette_t), rbind(toobject, I), power(outbox, TWO)), F0)))), add(multiply(shape_f(get_arg_rank_f(colorfilter(o_g(I, R5), color(get_nth_t(remove_f(get_nth_t(order(fgpartition(I), height_f), L1), order(fgpartition(I), height_f)), L1))), chain(chain(size, lbind(remove, get_color_rank_t(I, F0)), palette_t), rbind(toobject, I), power(outbox, TWO)), F0)), THREE), TWO_BY_TWO)))), apply(rbind(subtract, increment(shape_f(get_arg_rank_f(colorfilter(o_g(I, R5), color(get_nth_t(remove_f(get_nth_t(order(fgpartition(I), height_f), L1), order(fgpartition(I), height_f)), L1))), chain(chain(size, lbind(remove, get_color_rank_t(I, F0)), palette_t), rbind(toobject, I), power(outbox, TWO)), F0)))), apply(rbind(corner, R0), colorfilter(o_g(I, R5), color(get_nth_t(remove_f(get_nth_t(order(fgpartition(I), height_f), L1), order(fgpartition(I), height_f)), L1)))))))


def solve_39e1d7f9(S, I):
    x1 = o_g(I, R5)
    x2 = fgpartition(I)
    x3 = order(x2, height_f)
    x4 = get_nth_t(x3, L1)
    x5 = remove_f(x4, x3)
    x6 = get_nth_t(x5, L1)
    x7 = color(x6)
    x8 = colorfilter(x1, x7)
    x9 = get_color_rank_t(I, F0)
    x10 = lbind(remove, x9)
    x11 = chain(size, x10, palette_t)
    x12 = rbind(toobject, I)
    x13 = power(outbox, TWO)
    x14 = chain(x11, x12, x13)
    x15 = get_arg_rank_f(x8, x14, F0)
    x16 = corner(x15, R0)
    x17 = shape_f(x15)
    x18 = subtract(x16, x17)
    x19 = decrement(x18)
    x20 = multiply(x17, THREE)
    x21 = add(x20, TWO_BY_TWO)
    x22 = crop(I, x19, x21)
    x23 = asobject(x22)
    x24 = lbind(shift, x23)
    x25 = increment(x17)
    x26 = rbind(subtract, x25)
    x27 = rbind(corner, R0)
    x28 = apply(x27, x8)
    x29 = apply(x26, x28)
    x30 = mapply(x24, x29)
    O = paint(I, x30)
    return O
