def solve_234bbc79_one(S, I):
    return paint(canvas(ZERO, astuple(THREE, decrement(width_f(get_nth_f(power(fork(astuple, fork(combine, rbind(get_nth_f, F0), fork(shift, compose(rbind(get_nth_f, F0), rbind(get_nth_f, L1)), compose(lbind(add, RIGHT), fork(subtract, compose(compose(rbind(get_nth_f, L1), fork(rbind(get_arg_rank, L1), fork(sfilter, identity, compose(lbind(matcher, compose(rbind(get_nth_f, L1), rbind(get_nth_f, L1))), rbind(col_row, R3))), chain(lbind(rbind(chain, compose(dneighbors, rbind(get_nth_f, L1))), size), lbind(rbind, intersection), toindices))), rbind(get_nth_f, F0)), chain(compose(rbind(get_nth_f, L1), fork(rbind(get_arg_rank, L1), fork(sfilter, identity, compose(lbind(matcher, compose(rbind(get_nth_f, L1), rbind(get_nth_f, L1))), rbind(col_row, R2))), chain(lbind(rbind(chain, compose(dneighbors, rbind(get_nth_f, L1))), size), lbind(rbind, intersection), toindices))), rbind(get_nth_f, F0), rbind(get_nth_f, L1)))))), fork(remove, compose(rbind(get_nth_f, F0), rbind(get_nth_f, L1)), rbind(get_nth_f, L1))), size_f(o_g(I, R1)))(astuple(initset(astuple(ZERO, DOWN_LEFT)), order(apply(fork(recolor_o, compose(rbind(other, FIVE), palette_f), identity), o_g(I, R1)), rbind(col_row, R2)))), F0))))), get_nth_f(power(fork(astuple, fork(combine, rbind(get_nth_f, F0), fork(shift, compose(rbind(get_nth_f, F0), rbind(get_nth_f, L1)), compose(lbind(add, RIGHT), fork(subtract, compose(compose(rbind(get_nth_f, L1), fork(rbind(get_arg_rank, L1), fork(sfilter, identity, compose(lbind(matcher, compose(rbind(get_nth_f, L1), rbind(get_nth_f, L1))), rbind(col_row, R3))), chain(lbind(rbind(chain, compose(dneighbors, rbind(get_nth_f, L1))), size), lbind(rbind, intersection), toindices))), rbind(get_nth_f, F0)), chain(compose(rbind(get_nth_f, L1), fork(rbind(get_arg_rank, L1), fork(sfilter, identity, compose(lbind(matcher, compose(rbind(get_nth_f, L1), rbind(get_nth_f, L1))), rbind(col_row, R2))), chain(lbind(rbind(chain, compose(dneighbors, rbind(get_nth_f, L1))), size), lbind(rbind, intersection), toindices))), rbind(get_nth_f, F0), rbind(get_nth_f, L1)))))), fork(remove, compose(rbind(get_nth_f, F0), rbind(get_nth_f, L1)), rbind(get_nth_f, L1))), size_f(o_g(I, R1)))(astuple(initset(astuple(ZERO, DOWN_LEFT)), order(apply(fork(recolor_o, compose(rbind(other, FIVE), palette_f), identity), o_g(I, R1)), rbind(col_row, R2)))), F0))


def solve_234bbc79(S, I):
    x1 = rbind(get_nth_f, F0)
    x2 = rbind(get_nth_f, L1)
    x3 = compose(x1, x2)
    x4 = lbind(add, RIGHT)
    x5 = rbind(get_arg_rank, L1)
    x6 = compose(x2, x2)
    x7 = lbind(matcher, x6)
    x8 = rbind(col_row, R3)
    x9 = compose(x7, x8)
    x10 = fork(sfilter, identity, x9)
    x11 = compose(dneighbors, x2)
    x12 = rbind(chain, x11)
    x13 = lbind(x12, size)
    x14 = lbind(rbind, intersection)
    x15 = chain(x13, x14, toindices)
    x16 = fork(x5, x10, x15)
    x17 = compose(x2, x16)
    x18 = compose(x17, x1)
    x19 = rbind(col_row, R2)
    x20 = compose(x7, x19)
    x21 = fork(sfilter, identity, x20)
    x22 = fork(x5, x21, x15)
    x23 = compose(x2, x22)
    x24 = chain(x23, x1, x2)
    x25 = fork(subtract, x18, x24)
    x26 = compose(x4, x25)
    x27 = fork(shift, x3, x26)
    x28 = fork(combine, x1, x27)
    x29 = fork(remove, x3, x2)
    x30 = fork(astuple, x28, x29)
    x31 = o_g(I, R1)
    x32 = size_f(x31)
    x33 = power(x30, x32)
    x34 = astuple(ZERO, DOWN_LEFT)
    x35 = initset(x34)
    x36 = rbind(other, FIVE)
    x37 = compose(x36, palette_f)
    x38 = fork(recolor_o, x37, identity)
    x39 = apply(x38, x31)
    x40 = order(x39, x19)
    x41 = astuple(x35, x40)
    x42 = x33(x41)
    x43 = get_nth_f(x42, F0)
    x44 = width_f(x43)
    x45 = decrement(x44)
    x46 = astuple(THREE, x45)
    x47 = canvas(ZERO, x46)
    O = paint(x47, x43)
    return O
