def solve_50846271_one(S, I):
    return fill(fill(fill(I, TWO, mfilter_f(prapply(connect, f_ofcolor(I, TWO), f_ofcolor(I, TWO)), fork(both, compose(lbind(greater, SIX), size), fork(either, vline_i, hline_i)))), EIGHT, mapply(fork(combine, fork(connect, rbind(add, toivec(halve(get_val_rank_f(colorfilter(o_g(fill(I, TWO, mfilter_f(prapply(connect, f_ofcolor(I, TWO), f_ofcolor(I, TWO)), fork(both, compose(lbind(greater, SIX), size), fork(either, vline_i, hline_i)))), R4), TWO), width_f, F0)))), rbind(subtract, toivec(halve(get_val_rank_f(colorfilter(o_g(fill(I, TWO, mfilter_f(prapply(connect, f_ofcolor(I, TWO), f_ofcolor(I, TWO)), fork(both, compose(lbind(greater, SIX), size), fork(either, vline_i, hline_i)))), R4), TWO), width_f, F0))))), fork(connect, rbind(add, tojvec(halve(get_val_rank_f(colorfilter(o_g(fill(I, TWO, mfilter_f(prapply(connect, f_ofcolor(I, TWO), f_ofcolor(I, TWO)), fork(both, compose(lbind(greater, SIX), size), fork(either, vline_i, hline_i)))), R4), TWO), width_f, F0)))), rbind(subtract, tojvec(halve(get_val_rank_f(colorfilter(o_g(fill(I, TWO, mfilter_f(prapply(connect, f_ofcolor(I, TWO), f_ofcolor(I, TWO)), fork(both, compose(lbind(greater, SIX), size), fork(either, vline_i, hline_i)))), R4), TWO), width_f, F0)))))), apply(compose(rbind(rbind(get_arg_rank, F0), chain(rbind(colorcount_f, TWO), rbind(toobject, fill(I, TWO, mfilter_f(prapply(connect, f_ofcolor(I, TWO), f_ofcolor(I, TWO)), fork(both, compose(lbind(greater, SIX), size), fork(either, vline_i, hline_i))))), fork(combine, dneighbors, fork(insert, rbind(subtract, TWO_BY_ZERO), fork(insert, rbind(subtract, ZERO_BY_TWO), fork(insert, rbind(add, TWO_BY_ZERO), compose(initset, rbind(add, ZERO_BY_TWO)))))))), toindices), colorfilter(o_g(fill(I, TWO, mfilter_f(prapply(connect, f_ofcolor(I, TWO), f_ofcolor(I, TWO)), fork(both, compose(lbind(greater, SIX), size), fork(either, vline_i, hline_i)))), R4), TWO)))), TWO, f_ofcolor(I, TWO))


def solve_50846271(S, I):
    x1 = f_ofcolor(I, TWO)
    x2 = prapply(connect, x1, x1)
    x3 = lbind(greater, SIX)
    x4 = compose(x3, size)
    x5 = fork(either, vline_i, hline_i)
    x6 = fork(both, x4, x5)
    x7 = mfilter_f(x2, x6)
    x8 = fill(I, TWO, x7)
    x9 = o_g(x8, R4)
    x10 = colorfilter(x9, TWO)
    x11 = get_val_rank_f(x10, width_f, F0)
    x12 = halve(x11)
    x13 = toivec(x12)
    x14 = rbind(add, x13)
    x15 = rbind(subtract, x13)
    x16 = fork(connect, x14, x15)
    x17 = tojvec(x12)
    x18 = rbind(add, x17)
    x19 = rbind(subtract, x17)
    x20 = fork(connect, x18, x19)
    x21 = fork(combine, x16, x20)
    x22 = rbind(get_arg_rank, F0)
    x23 = rbind(colorcount_f, TWO)
    x24 = rbind(toobject, x8)
    x25 = rbind(subtract, TWO_BY_ZERO)
    x26 = rbind(subtract, ZERO_BY_TWO)
    x27 = rbind(add, TWO_BY_ZERO)
    x28 = rbind(add, ZERO_BY_TWO)
    x29 = compose(initset, x28)
    x30 = fork(insert, x27, x29)
    x31 = fork(insert, x26, x30)
    x32 = fork(insert, x25, x31)
    x33 = fork(combine, dneighbors, x32)
    x34 = chain(x23, x24, x33)
    x35 = rbind(x22, x34)
    x36 = compose(x35, toindices)
    x37 = apply(x36, x10)
    x38 = mapply(x21, x37)
    x39 = fill(x8, EIGHT, x38)
    O = fill(x39, TWO, x1)
    return O
