# Generated by tokpidjin/card.py

from pile import *
from gpu_env import GPUEnv as Env
from safe_dsl import _get_safe_default
from batt_gpu import batch_process_samples_gpu

def batt(task_id, S, I, C, log_path):
    s = []
    o = []
    # Pre-mutate: t1 - differ = True - solver = False - old_items = ['identity', ' p_g'] - old_hints = ['Any', 'Any']
    t1 = identity(p_g)
    # Pre-mutate: t2 - differ = True - solver = False - old_items = ['t1', ' I'] - old_hints = None
    t2 = t1(I)
    # Pre-mutate: t3 - differ = True - solver = False - old_items = ['t1', ' C'] - old_hints = None
    t3 = t1(C)
    # Pre-mutate: t4 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t2'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t4 = difference_tuple(t3, t2)
    # Pre-mutate: t5 - differ = True - solver = False - old_items = ['size', ' t4'] - old_hints = ['Integer', 'Container']
    t5 = size(t4)
    # Pre-mutate: t6 - differ = True - solver = True - old_items = ['get_nth_t', ' t4', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t6 = get_nth_t(t4, F0)
    # Pre-mutate: t7 - differ = True - solver = False - old_items = ['astuple', ' t5', ' t6'] - old_hints = ['Tuple', 'Any', 'Any']
    t7 = astuple(t5, t6)
    s.append((7, 'None', 'differ_c59e6ae069a9205b311cf67a15473d64', t7))
    # Pre-mutate: t8 - differ = True - solver = False - old_items = ['rbind', ' o_g', ' R5'] - old_hints = ['Callable', 'Callable', 'Any']
    t8 = rbind(o_g, R5)
    # Pre-mutate: t9 - differ = True - solver = False - old_items = ['t8', ' I'] - old_hints = None
    t9 = t8(I)
    # Pre-mutate: t10 - differ = True - solver = False - old_items = ['t8', ' C'] - old_hints = None
    t10 = t8(C)
    # Pre-mutate: t11 - differ = True - solver = False - old_items = ['rbind', ' sizefilter', ' ONE'] - old_hints = ['Callable', 'Callable', 'Any']
    t11 = rbind(sizefilter, ONE)
    # Pre-mutate: t12 - differ = True - solver = False - old_items = ['t11', ' t9'] - old_hints = None
    t12 = t11(t9)
    # Pre-mutate: t13 - differ = True - solver = False - old_items = ['t11', ' t10'] - old_hints = None
    t13 = t11(t10)
    # Pre-mutate: t14 - differ = True - solver = False - old_items = ['difference', ' t12', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t14 = difference(t12, t13)
    # Pre-mutate: t15 - differ = True - solver = False - old_items = ['size', ' t14'] - old_hints = ['Integer', 'Container']
    t15 = size(t14)
    # Pre-mutate: t16 - differ = True - solver = True - old_items = ['get_nth_f', ' t14', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t16 = get_nth_f(t14, F0)
    # Pre-mutate: t17 - differ = True - solver = False - old_items = ['astuple', ' t15', ' t16'] - old_hints = ['Tuple', 'Any', 'Any']
    t17 = astuple(t15, t16)
    s.append((17, 'None', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t17))
    # Pre-mutate: t18 - differ = True - solver = False - old_items = ['difference', ' t13', ' t12'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t18 = difference(t13, t12)
    # Pre-mutate: t19 - differ = True - solver = False - old_items = ['size', ' t18'] - old_hints = ['Integer', 'Container']
    t19 = size(t18)
    # Pre-mutate: t20 - differ = True - solver = True - old_items = ['get_nth_f', ' t18', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t20 = get_nth_f(t18, F0)
    # Pre-mutate: t21 - differ = True - solver = False - old_items = ['astuple', ' t19', ' t20'] - old_hints = ['Tuple', 'Any', 'Any']
    t21 = astuple(t19, t20)
    s.append((21, 'None', 'differ_f4a4346405e974b919a4b5a52f28e40c', t21))
    # Pre-mutate: t22 - differ = True - solver = False - old_items = ['difference_tuple', ' t2', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t22 = difference_tuple(t2, t3)
    # Pre-mutate: t23 - differ = True - solver = False - old_items = ['size', ' t22'] - old_hints = ['Integer', 'Container']
    t23 = size(t22)
    # Pre-mutate: t24 - differ = True - solver = True - old_items = ['get_nth_t', ' t22', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t24 = get_nth_t(t22, F0)
    # Pre-mutate: t25 - differ = True - solver = False - old_items = ['astuple', ' t23', ' t24'] - old_hints = ['Tuple', 'Any', 'Any']
    t25 = astuple(t23, t24)
    s.append((25, 'None', 'differ_fc9e44c913711da609a9e25126b4b296', t25))
    # Pre-mutate: t26 - differ = False - solver = True - old_items = ['replace', ' I', ' TWO', ' ZERO'] - old_hints = ['Grid', 'Grid', 'C_', 'C_']
    # GPU Batch Pattern: Sample processing (t26-t29)
    t26, t27, t28, t29 = batch_process_samples_gpu(S)
    t30 = dedupe(t28)
    t31 = dedupe(t29)
    t32 = difference_tuple(t30, t31)
    t33 = get_nth_t(t32, F0)
    t34 = replace(I, TWO, BLACK)
    # Pre-mutate: t35 - differ = False - solver = True - old_items = ['o_g', ' I', ' R5'] - old_hints = ['Objects', 'Grid', 'R8']
    t35 = o_g(I, R5)
    # Pre-mutate: t36 - differ = False - solver = True - old_items = ['mir_rot_t', ' I', ' R1'] - old_hints = ['Grid', 'Grid', 'A8']
    t36 = identity(S)
    t37 = a_mr(t36)
    t38 = mir_rot_t(I, t37)
    o.append((38, True, '9dfd6313', t38))
    # Pre-mutate: t39 - differ = True - solver = False - old_items = ['t1', ' t38'] - old_hints = None
    t39 = t1(t38)
    # Pre-mutate: t40 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t39'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t40 = difference_tuple(t3, t39)
    # Pre-mutate: t41 - differ = True - solver = False - old_items = ['size', ' t40'] - old_hints = ['Integer', 'Container']
    t41 = size(t40)
    # Pre-mutate: t42 - differ = True - solver = True - old_items = ['get_nth_t', ' t40', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t42 = get_nth_t(t40, F0)
    # Pre-mutate: t43 - differ = True - solver = False - old_items = ['astuple', ' t41', ' t42'] - old_hints = ['Tuple', 'Any', 'Any']
    t43 = astuple(t41, t42)
    s.append((43, '9dfd6313', 'differ_c59e6ae069a9205b311cf67a15473d64', t43))
    # Pre-mutate: t44 - differ = True - solver = False - old_items = ['t8', ' t38'] - old_hints = None
    t44 = t8(t38)
    # Pre-mutate: t45 - differ = True - solver = False - old_items = ['t11', ' t44'] - old_hints = None
    t45 = t11(t44)
    # Pre-mutate: t46 - differ = True - solver = False - old_items = ['difference', ' t45', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t46 = difference(t45, t13)
    # Pre-mutate: t47 - differ = True - solver = False - old_items = ['size', ' t46'] - old_hints = ['Integer', 'Container']
    t47 = size(t46)
    # Pre-mutate: t48 - differ = True - solver = True - old_items = ['get_nth_f', ' t46', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t48 = get_nth_f(t46, F0)
    # Pre-mutate: t49 - differ = True - solver = False - old_items = ['astuple', ' t47', ' t48'] - old_hints = ['Tuple', 'Any', 'Any']
    t49 = astuple(t47, t48)
    s.append((49, '9dfd6313', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t49))
    # Pre-mutate: t50 - differ = True - solver = False - old_items = ['difference', ' t13', ' t45'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t50 = difference(t13, t45)
    # Pre-mutate: t51 - differ = True - solver = False - old_items = ['size', ' t50'] - old_hints = ['Integer', 'Container']
    t51 = size(t50)
    # Pre-mutate: t52 - differ = True - solver = True - old_items = ['get_nth_f', ' t50', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t52 = get_nth_f(t50, F0)
    # Pre-mutate: t53 - differ = True - solver = False - old_items = ['astuple', ' t51', ' t52'] - old_hints = ['Tuple', 'Any', 'Any']
    t53 = astuple(t51, t52)
    s.append((53, '9dfd6313', 'differ_f4a4346405e974b919a4b5a52f28e40c', t53))
    # Pre-mutate: t54 - differ = True - solver = False - old_items = ['difference_tuple', ' t39', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t54 = difference_tuple(t39, t3)
    # Pre-mutate: t55 - differ = True - solver = False - old_items = ['size', ' t54'] - old_hints = ['Integer', 'Container']
    t55 = size(t54)
    # Pre-mutate: t56 - differ = True - solver = True - old_items = ['get_nth_t', ' t54', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t56 = get_nth_t(t54, F0)
    # Pre-mutate: t57 - differ = True - solver = False - old_items = ['astuple', ' t55', ' t56'] - old_hints = ['Tuple', 'Any', 'Any']
    t57 = astuple(t55, t56)
    s.append((57, '9dfd6313', 'differ_fc9e44c913711da609a9e25126b4b296', t57))
    # Pre-mutate: t58 - differ = False - solver = True - old_items = ['compose', ' backdrop', ' inbox'] - old_hints = ['Callable', 'Callable', 'Callable']
    t58 = compose(backdrop, inbox)
    # Pre-mutate: t59 - differ = False - solver = True - old_items = ['colorfilter', ' t35', ' TWO'] - old_hints = ['Objects', 'Objects', 'C_']
    t59 = colorfilter(t35, RED)
    # Pre-mutate: t60 - differ = False - solver = True - old_items = ['merge_f', ' t35'] - old_hints = ['Container', 'ContainerContainer']
    t60 = merge_f(t35)
    # Pre-mutate: t61 - differ = False - solver = True - old_items = ['mapply', ' corners', ' t35'] - old_hints = ['FrozenSet', 'Callable', 'ContainerContainer']
    t61 = mapply(corners, t35)
    # Pre-mutate: t62 - differ = False - solver = True - old_items = ['get_nth_f', ' t59', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t62 = get_nth_f(t59, F0)
    # Pre-mutate: t63 - differ = False - solver = True - old_items = ['rbind', ' get_arg_rank', ' F0'] - old_hints = ['Callable', 'Callable', 'Any']
    t63 = rbind(get_arg_rank, F0)
    # Pre-mutate: t64 - differ = False - solver = True - old_items = ['underfill', ' I', ' ONE', ' t61'] - old_hints = ['Grid', 'Grid', 'C_', 'Patch']
    # GPU Batch Pattern: Sample processing (t64-t67)
    t64, t65, t66, t67 = batch_process_samples_gpu(S)
    t68 = dedupe(t66)
    t69 = dedupe(t67)
    t70 = difference_tuple(t69, t68)
    t71 = get_nth_t(t70, F0)
    t72 = underfill(I, t71, t61)
    o.append((72, True, '3aa6fb7a', t72))
    # Pre-mutate: t73 - differ = True - solver = False - old_items = ['t1', ' t72'] - old_hints = None
    t73 = t1(t72)
    # Pre-mutate: t74 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t73'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t74 = difference_tuple(t3, t73)
    # Pre-mutate: t75 - differ = True - solver = False - old_items = ['size', ' t74'] - old_hints = ['Integer', 'Container']
    t75 = size(t74)
    # Pre-mutate: t76 - differ = True - solver = True - old_items = ['get_nth_t', ' t74', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t76 = get_nth_t(t74, F0)
    # Pre-mutate: t77 - differ = True - solver = False - old_items = ['astuple', ' t75', ' t76'] - old_hints = ['Tuple', 'Any', 'Any']
    t77 = astuple(t75, t76)
    s.append((77, '3aa6fb7a', 'differ_c59e6ae069a9205b311cf67a15473d64', t77))
    # Pre-mutate: t78 - differ = True - solver = False - old_items = ['t8', ' t72'] - old_hints = None
    t78 = t8(t72)
    # Pre-mutate: t79 - differ = True - solver = False - old_items = ['t11', ' t78'] - old_hints = None
    t79 = t11(t78)
    # Pre-mutate: t80 - differ = True - solver = False - old_items = ['difference', ' t79', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t80 = difference(t79, t13)
    # Pre-mutate: t81 - differ = True - solver = False - old_items = ['size', ' t80'] - old_hints = ['Integer', 'Container']
    t81 = size(t80)
    # Pre-mutate: t82 - differ = True - solver = True - old_items = ['get_nth_f', ' t80', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t82 = get_nth_f(t80, F0)
    # Pre-mutate: t83 - differ = True - solver = False - old_items = ['astuple', ' t81', ' t82'] - old_hints = ['Tuple', 'Any', 'Any']
    t83 = astuple(t81, t82)
    s.append((83, '3aa6fb7a', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t83))
    # Pre-mutate: t84 - differ = True - solver = False - old_items = ['difference', ' t13', ' t79'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t84 = difference(t13, t79)
    # Pre-mutate: t85 - differ = True - solver = False - old_items = ['size', ' t84'] - old_hints = ['Integer', 'Container']
    t85 = size(t84)
    # Pre-mutate: t86 - differ = True - solver = True - old_items = ['get_nth_f', ' t84', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t86 = get_nth_f(t84, F0)
    # Pre-mutate: t87 - differ = True - solver = False - old_items = ['astuple', ' t85', ' t86'] - old_hints = ['Tuple', 'Any', 'Any']
    t87 = astuple(t85, t86)
    s.append((87, '3aa6fb7a', 'differ_f4a4346405e974b919a4b5a52f28e40c', t87))
    # Pre-mutate: t88 - differ = True - solver = False - old_items = ['difference_tuple', ' t73', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t88 = difference_tuple(t73, t3)
    # Pre-mutate: t89 - differ = True - solver = False - old_items = ['size', ' t88'] - old_hints = ['Integer', 'Container']
    t89 = size(t88)
    # Pre-mutate: t90 - differ = True - solver = True - old_items = ['get_nth_t', ' t88', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t90 = get_nth_t(t88, F0)
    # Pre-mutate: t91 - differ = True - solver = False - old_items = ['astuple', ' t89', ' t90'] - old_hints = ['Tuple', 'Any', 'Any']
    t91 = astuple(t89, t90)
    s.append((91, '3aa6fb7a', 'differ_fc9e44c913711da609a9e25126b4b296', t91))
    # Pre-mutate: t92 - differ = False - solver = True - old_items = ['sfilter_f', ' t61', ' square_f'] - old_hints = ['FrozenSet', 'FrozenSet', 'Callable']
    t92 = sfilter_f(t61, square_f)
    # Pre-mutate: t93 - differ = False - solver = True - old_items = ['colorfilter', ' t35', ' EIGHT'] - old_hints = ['Objects', 'Objects', 'C_']
    t93 = colorfilter(t35, CYAN)
    # Pre-mutate: t94 - differ = False - solver = True - old_items = ['rbind', ' col_row', ' R3'] - old_hints = ['Callable', 'Callable', 'Any']
    t94 = rbind(col_row, t76)
    # Pre-mutate: t95 - differ = False - solver = True - old_items = ['difference', ' t61', ' t92'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t95 = difference(t61, t92)
    # Pre-mutate: t96 - differ = False - solver = True - old_items = ['get_nth_f', ' t93', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t96 = get_nth_f(t93, F0)
    # Pre-mutate: t97 - differ = False - solver = True - old_items = ['rbind', ' t63', ' t94'] - old_hints = ['Callable', 'Callable', 'Any']
    t97 = rbind(t63, t94)
    # Pre-mutate: t98 - differ = False - solver = True - old_items = ['mapply', ' t58', ' t95'] - old_hints = ['FrozenSet', 'Callable', 'ContainerContainer']
    t98 = mapply(t58, t95)
    # Pre-mutate: t99 - differ = False - solver = True - old_items = ['gravitate', ' t62', ' t96'] - old_hints = ['IJ', 'Patch', 'Patch']
    t99 = gravitate(t62, t96)
    # Pre-mutate: t100 - differ = False - solver = True - old_items = ['lbind', ' colorfilter', ' t35'] - old_hints = ['Callable', 'Callable', 'Any']
    t100 = lbind(colorfilter, t35)
    # Pre-mutate: t101 - differ = False - solver = True - old_items = ['fill', ' t34', ' THREE', ' t98'] - old_hints = ['Grid', 'Grid', 'C_', 'Patch']
    # GPU Batch Pattern: Sample processing (t101-t104)
    t101, t102, t103, t104 = batch_process_samples_gpu(S)
    t105 = dedupe(t103)
    t106 = dedupe(t104)
    t107 = difference_tuple(t106, t105)
    t108 = get_nth_t(t107, F0)
    t109 = fill(t34, t108, t98)
    o.append((109, True, 'd5d6de2d', t109))
    # Pre-mutate: t110 - differ = True - solver = False - old_items = ['t1', ' t109'] - old_hints = None
    t110 = t1(t109)
    # Pre-mutate: t111 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t110'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t111 = difference_tuple(t3, t110)
    # Pre-mutate: t112 - differ = True - solver = False - old_items = ['size', ' t111'] - old_hints = ['Integer', 'Container']
    t112 = size(t111)
    # Pre-mutate: t113 - differ = True - solver = True - old_items = ['get_nth_t', ' t111', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t113 = get_nth_t(t111, F0)
    # Pre-mutate: t114 - differ = True - solver = False - old_items = ['astuple', ' t112', ' t113'] - old_hints = ['Tuple', 'Any', 'Any']
    t114 = astuple(t112, t113)
    s.append((114, 'd5d6de2d', 'differ_c59e6ae069a9205b311cf67a15473d64', t114))
    # Pre-mutate: t115 - differ = True - solver = False - old_items = ['t8', ' t109'] - old_hints = None
    t115 = t8(t109)
    # Pre-mutate: t116 - differ = True - solver = False - old_items = ['t11', ' t115'] - old_hints = None
    t116 = t11(t115)
    # Pre-mutate: t117 - differ = True - solver = False - old_items = ['difference', ' t116', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t117 = difference(t116, t13)
    # Pre-mutate: t118 - differ = True - solver = False - old_items = ['size', ' t117'] - old_hints = ['Integer', 'Container']
    t118 = size(t117)
    # Pre-mutate: t119 - differ = True - solver = True - old_items = ['get_nth_f', ' t117', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t119 = get_nth_f(t117, F0)
    # Pre-mutate: t120 - differ = True - solver = False - old_items = ['astuple', ' t118', ' t119'] - old_hints = ['Tuple', 'Any', 'Any']
    t120 = astuple(t118, t119)
    s.append((120, 'd5d6de2d', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t120))
    # Pre-mutate: t121 - differ = True - solver = False - old_items = ['difference', ' t13', ' t116'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t121 = difference(t13, t116)
    # Pre-mutate: t122 - differ = True - solver = False - old_items = ['size', ' t121'] - old_hints = ['Integer', 'Container']
    t122 = size(t121)
    # Pre-mutate: t123 - differ = True - solver = True - old_items = ['get_nth_f', ' t121', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t123 = get_nth_f(t121, F0)
    # Pre-mutate: t124 - differ = True - solver = False - old_items = ['astuple', ' t122', ' t123'] - old_hints = ['Tuple', 'Any', 'Any']
    t124 = astuple(t122, t123)
    s.append((124, 'd5d6de2d', 'differ_f4a4346405e974b919a4b5a52f28e40c', t124))
    # Pre-mutate: t125 - differ = True - solver = False - old_items = ['difference_tuple', ' t110', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t125 = difference_tuple(t110, t3)
    # Pre-mutate: t126 - differ = True - solver = False - old_items = ['size', ' t125'] - old_hints = ['Integer', 'Container']
    t126 = size(t125)
    # Pre-mutate: t127 - differ = True - solver = True - old_items = ['get_nth_t', ' t125', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t127 = get_nth_t(t125, F0)
    # Pre-mutate: t128 - differ = True - solver = False - old_items = ['astuple', ' t126', ' t127'] - old_hints = ['Tuple', 'Any', 'Any']
    t128 = astuple(t126, t127)
    s.append((128, 'd5d6de2d', 'differ_fc9e44c913711da609a9e25126b4b296', t128))
    # Pre-mutate: t129 - differ = False - solver = True - old_items = ['move', ' I', ' t62', ' t99'] - old_hints = ['Grid', 'Grid', 'Object', 'IJ']
    t129 = move(I, t62, t99)
    o.append((129, False, '05f2a901', t129))
    # Pre-mutate: t130 - differ = True - solver = False - old_items = ['t1', ' t129'] - old_hints = None
    t130 = t1(t129)
    # Pre-mutate: t131 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t130'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t131 = difference_tuple(t3, t130)
    # Pre-mutate: t132 - differ = True - solver = False - old_items = ['size', ' t131'] - old_hints = ['Integer', 'Container']
    t132 = size(t131)
    # Pre-mutate: t133 - differ = True - solver = True - old_items = ['get_nth_t', ' t131', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t133 = get_nth_t(t131, F0)
    # Pre-mutate: t134 - differ = True - solver = False - old_items = ['astuple', ' t132', ' t133'] - old_hints = ['Tuple', 'Any', 'Any']
    t134 = astuple(t132, t133)
    s.append((134, '05f2a901', 'differ_c59e6ae069a9205b311cf67a15473d64', t134))
    # Pre-mutate: t135 - differ = True - solver = False - old_items = ['t8', ' t129'] - old_hints = None
    t135 = t8(t129)
    # Pre-mutate: t136 - differ = True - solver = False - old_items = ['t11', ' t135'] - old_hints = None
    t136 = t11(t135)
    # Pre-mutate: t137 - differ = True - solver = False - old_items = ['difference', ' t136', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t137 = difference(t136, t13)
    # Pre-mutate: t138 - differ = True - solver = False - old_items = ['size', ' t137'] - old_hints = ['Integer', 'Container']
    t138 = size(t137)
    # Pre-mutate: t139 - differ = True - solver = True - old_items = ['get_nth_f', ' t137', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t139 = get_nth_f(t137, F0)
    # Pre-mutate: t140 - differ = True - solver = False - old_items = ['astuple', ' t138', ' t139'] - old_hints = ['Tuple', 'Any', 'Any']
    t140 = astuple(t138, t139)
    s.append((140, '05f2a901', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t140))
    # Pre-mutate: t141 - differ = True - solver = False - old_items = ['difference', ' t13', ' t136'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t141 = difference(t13, t136)
    # Pre-mutate: t142 - differ = True - solver = False - old_items = ['size', ' t141'] - old_hints = ['Integer', 'Container']
    t142 = size(t141)
    # Pre-mutate: t143 - differ = True - solver = True - old_items = ['get_nth_f', ' t141', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t143 = get_nth_f(t141, F0)
    # Pre-mutate: t144 - differ = True - solver = False - old_items = ['astuple', ' t142', ' t143'] - old_hints = ['Tuple', 'Any', 'Any']
    t144 = astuple(t142, t143)
    s.append((144, '05f2a901', 'differ_f4a4346405e974b919a4b5a52f28e40c', t144))
    # Pre-mutate: t145 - differ = True - solver = False - old_items = ['difference_tuple', ' t130', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t145 = difference_tuple(t130, t3)
    # Pre-mutate: t146 - differ = True - solver = False - old_items = ['size', ' t145'] - old_hints = ['Integer', 'Container']
    t146 = size(t145)
    # Pre-mutate: t147 - differ = True - solver = True - old_items = ['get_nth_t', ' t145', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t147 = get_nth_t(t145, F0)
    # Pre-mutate: t148 - differ = True - solver = False - old_items = ['astuple', ' t146', ' t147'] - old_hints = ['Tuple', 'Any', 'Any']
    t148 = astuple(t146, t147)
    s.append((148, '05f2a901', 'differ_fc9e44c913711da609a9e25126b4b296', t148))
    # Pre-mutate: t149 - differ = False - solver = True - old_items = ['compose', ' t97', ' t100'] - old_hints = ['Callable', 'Callable', 'Callable']
    t149 = compose(t97, t100)
    # Pre-mutate: t150 - differ = False - solver = True - old_items = ['apply', ' color', ' t35'] - old_hints = ['Container', 'Callable', 'Container']
    t150 = apply(color, t35)
    # Pre-mutate: t151 - differ = False - solver = True - old_items = ['mapply', ' t149', ' t150'] - old_hints = ['FrozenSet', 'Callable', 'ContainerContainer']
    t151 = mapply(t149, t150)
    # Pre-mutate: t152 - differ = False - solver = True - old_items = ['difference', ' t60', ' t151'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t152 = difference(t60, t151)
    # Pre-mutate: t153 - differ = False - solver = True - old_items = ['move', ' I', ' t152', ' RIGHT'] - old_hints = ['Grid', 'Grid', 'Object', 'IJ']
    t153 = move(I, t152, RIGHT)
    o.append((153, False, '025d127b', t153))
    # Pre-mutate: t154 - differ = True - solver = False - old_items = ['t1', ' t153'] - old_hints = None
    t154 = t1(t153)
    # Pre-mutate: t155 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t154'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t155 = difference_tuple(t3, t154)
    # Pre-mutate: t156 - differ = True - solver = False - old_items = ['size', ' t155'] - old_hints = ['Integer', 'Container']
    t156 = size(t155)
    # Pre-mutate: t157 - differ = True - solver = True - old_items = ['get_nth_t', ' t155', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t157 = get_nth_t(t155, F0)
    # Pre-mutate: t158 - differ = True - solver = False - old_items = ['astuple', ' t156', ' t157'] - old_hints = ['Tuple', 'Any', 'Any']
    t158 = astuple(t156, t157)
    s.append((158, '025d127b', 'differ_c59e6ae069a9205b311cf67a15473d64', t158))
    # Pre-mutate: t159 - differ = True - solver = False - old_items = ['t8', ' t153'] - old_hints = None
    t159 = t8(t153)
    # Pre-mutate: t160 - differ = True - solver = False - old_items = ['t11', ' t159'] - old_hints = None
    t160 = t11(t159)
    # Pre-mutate: t161 - differ = True - solver = False - old_items = ['difference', ' t160', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t161 = difference(t160, t13)
    # Pre-mutate: t162 - differ = True - solver = False - old_items = ['size', ' t161'] - old_hints = ['Integer', 'Container']
    t162 = size(t161)
    # Pre-mutate: t163 - differ = True - solver = True - old_items = ['get_nth_f', ' t161', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t163 = get_nth_f(t161, F0)
    # Pre-mutate: t164 - differ = True - solver = False - old_items = ['astuple', ' t162', ' t163'] - old_hints = ['Tuple', 'Any', 'Any']
    t164 = astuple(t162, t163)
    s.append((164, '025d127b', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t164))
    # Pre-mutate: t165 - differ = True - solver = False - old_items = ['difference', ' t13', ' t160'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    t165 = difference(t13, t160)
    # Pre-mutate: t166 - differ = True - solver = False - old_items = ['size', ' t165'] - old_hints = ['Integer', 'Container']
    t166 = size(t165)
    # Pre-mutate: t167 - differ = True - solver = True - old_items = ['get_nth_f', ' t165', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    t167 = get_nth_f(t165, F0)
    # Pre-mutate: t168 - differ = True - solver = False - old_items = ['astuple', ' t166', ' t167'] - old_hints = ['Tuple', 'Any', 'Any']
    t168 = astuple(t166, t167)
    s.append((168, '025d127b', 'differ_f4a4346405e974b919a4b5a52f28e40c', t168))
    # Pre-mutate: t169 - differ = True - solver = False - old_items = ['difference_tuple', ' t154', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    t169 = difference_tuple(t154, t3)
    # Pre-mutate: t170 - differ = True - solver = False - old_items = ['size', ' t169'] - old_hints = ['Integer', 'Container']
    t170 = size(t169)
    # Pre-mutate: t171 - differ = True - solver = True - old_items = ['get_nth_t', ' t169', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    t171 = get_nth_t(t169, F0)
    # Pre-mutate: t172 - differ = True - solver = False - old_items = ['astuple', ' t170', ' t171'] - old_hints = ['Tuple', 'Any', 'Any']
    t172 = astuple(t170, t171)
    s.append((172, '025d127b', 'differ_fc9e44c913711da609a9e25126b4b296', t172))
    return o, s
