def solve_a8c38be5_one(S, I):
    return paint(canvas(FIVE, astuple(NINE, NINE)), mapply(fork(shift, identity, compose(chain(rbind(corner, R0), lbind(extract, apply(toindices, o_g(fill(canvas(FIVE, astuple(NINE, NINE)), ONE, combine(difference(box(asindices(canvas(FIVE, astuple(NINE, NINE)))), mapply(chain(outbox, outbox, initset), corners(asindices(canvas(FIVE, astuple(NINE, NINE)))))), sfilter_f(inbox(box(asindices(canvas(FIVE, astuple(NINE, NINE))))), compose(lbind(contained, ZERO), rbind(subtract, center(asindices(canvas(FIVE, astuple(NINE, NINE))))))))), R5))), lbind(matcher, normalize)), toindices)), apply(normalize, o_g(replace(I, FIVE, ZERO), R5))))


def solve_a8c38be5(S, I):
    x1 = astuple(NINE, NINE)
    x2 = canvas(FIVE, x1)
    x3 = rbind(corner, R0)
    x4 = asindices(x2)
    x5 = box(x4)
    x6 = chain(outbox, outbox, initset)
    x7 = corners(x4)
    x8 = mapply(x6, x7)
    x9 = difference(x5, x8)
    x10 = inbox(x5)
    x11 = lbind(contained, ZERO)
    x12 = center(x4)
    x13 = rbind(subtract, x12)
    x14 = compose(x11, x13)
    x15 = sfilter_f(x10, x14)
    x16 = combine(x9, x15)
    x17 = fill(x2, ONE, x16)
    x18 = o_g(x17, R5)
    x19 = apply(toindices, x18)
    x20 = lbind(extract, x19)
    x21 = lbind(matcher, normalize)
    x22 = chain(x3, x20, x21)
    x23 = compose(x22, toindices)
    x24 = fork(shift, identity, x23)
    x25 = replace(I, FIVE, ZERO)
    x26 = o_g(x25, R5)
    x27 = apply(normalize, x26)
    x28 = mapply(x24, x27)
    O = paint(x2, x28)
    return O
