def solve_d22278a0_one(S, I):
    return paint(I, mapply(fork(recolor_i, color, fork(intersection, fork(intersection, chain(lbind(sfilter, asindices(I)), lbind(compose, compose(chain(even, rbind(get_rank, F0), lbind(apply, fork(multiply, sign, identity))), fork(subtract, rbind(get_nth_f, F0), compose(center, rbind(get_nth_f, L1))))), lbind(rbind, astuple)), chain(lbind(sfilter, asindices(I)), rbind(compose, compose(lbind(rbind(get_arg_rank, L1), o_g(I, R5)), compose(lbind(compose, chain(fork(add, rbind(get_nth_f, F0), rbind(get_nth_f, L1)), lbind(apply, fork(multiply, sign, identity)), fork(subtract, rbind(get_nth_f, F0), compose(center, rbind(get_nth_f, L1))))), lbind(lbind, astuple)))), lbind(rbind, equality))), compose(lbind(sfilter, asindices(I)), fork(lbind(fork, greater), chain(rbind(compose, compose(lbind(compose, chain(fork(add, rbind(get_nth_f, F0), rbind(get_nth_f, L1)), lbind(apply, fork(multiply, sign, identity)), fork(subtract, rbind(get_nth_f, F0), compose(center, rbind(get_nth_f, L1))))), lbind(lbind, astuple))), lbind(lbind, rbind(get_val_rank, L1)), rbind(remove, o_g(I, R5))), compose(lbind(compose, chain(fork(add, rbind(get_nth_f, F0), rbind(get_nth_f, L1)), lbind(apply, fork(multiply, sign, identity)), fork(subtract, rbind(get_nth_f, F0), compose(center, rbind(get_nth_f, L1))))), lbind(rbind, astuple)))))), o_g(I, R5)))


def solve_d22278a0(S, I):
    x1 = asindices(I)
    x2 = lbind(sfilter, x1)
    x3 = rbind(get_rank, F0)
    x4 = fork(multiply, sign, identity)
    x5 = lbind(apply, x4)
    x6 = chain(even, x3, x5)
    x7 = rbind(get_nth_f, F0)
    x8 = rbind(get_nth_f, L1)
    x9 = compose(center, x8)
    x10 = fork(subtract, x7, x9)
    x11 = compose(x6, x10)
    x12 = lbind(compose, x11)
    x13 = lbind(rbind, astuple)
    x14 = chain(x2, x12, x13)
    x15 = rbind(get_arg_rank, L1)
    x16 = o_g(I, R5)
    x17 = lbind(x15, x16)
    x18 = fork(add, x7, x8)
    x19 = chain(x18, x5, x10)
    x20 = lbind(compose, x19)
    x21 = lbind(lbind, astuple)
    x22 = compose(x20, x21)
    x23 = compose(x17, x22)
    x24 = rbind(compose, x23)
    x25 = lbind(rbind, equality)
    x26 = chain(x2, x24, x25)
    x27 = fork(intersection, x14, x26)
    x28 = lbind(fork, greater)
    x29 = rbind(compose, x22)
    x30 = rbind(get_val_rank, L1)
    x31 = lbind(lbind, x30)
    x32 = rbind(remove, x16)
    x33 = chain(x29, x31, x32)
    x34 = compose(x20, x13)
    x35 = fork(x28, x33, x34)
    x36 = compose(x2, x35)
    x37 = fork(intersection, x27, x36)
    x38 = fork(recolor_i, color, x37)
    x39 = mapply(x38, x16)
    O = paint(I, x39)
    return O
