def solve_508bd3b6_one(S, I):
    return paint(paint(fill(paint(fill(I, THREE, connect(add(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), corner(get_arg_rank_f(o_g(I, R7), size, L1), R0), corner(get_arg_rank_f(o_g(I, R7), size, L1), R1)), double(multiply(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), UNITY, DOWN_LEFT), width_t(I)))), subtract(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), corner(get_arg_rank_f(o_g(I, R7), size, L1), R0), corner(get_arg_rank_f(o_g(I, R7), size, L1), R1)), double(multiply(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), UNITY, DOWN_LEFT), width_t(I)))))), get_arg_rank_f(o_g(I, R7), size, F0)), THREE, connect(add(get_nth_t(get_nth_f(extract(o_g(paint(fill(I, THREE, connect(add(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), corner(get_arg_rank_f(o_g(I, R7), size, L1), R0), corner(get_arg_rank_f(o_g(I, R7), size, L1), R1)), double(multiply(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), UNITY, DOWN_LEFT), width_t(I)))), subtract(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), corner(get_arg_rank_f(o_g(I, R7), size, L1), R0), corner(get_arg_rank_f(o_g(I, R7), size, L1), R1)), double(multiply(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), UNITY, DOWN_LEFT), width_t(I)))))), get_arg_rank_f(o_g(I, R7), size, F0)), R5), rbind(adjacent, get_arg_rank_f(o_g(I, R7), size, F0))), F0), L1), double(multiply(branch(flip(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT)), UNITY, DOWN_LEFT), width_t(I)))), subtract(get_nth_t(get_nth_f(extract(o_g(paint(fill(I, THREE, connect(add(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), corner(get_arg_rank_f(o_g(I, R7), size, L1), R0), corner(get_arg_rank_f(o_g(I, R7), size, L1), R1)), double(multiply(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), UNITY, DOWN_LEFT), width_t(I)))), subtract(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), corner(get_arg_rank_f(o_g(I, R7), size, L1), R0), corner(get_arg_rank_f(o_g(I, R7), size, L1), R1)), double(multiply(branch(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT), UNITY, DOWN_LEFT), width_t(I)))))), get_arg_rank_f(o_g(I, R7), size, F0)), R5), rbind(adjacent, get_arg_rank_f(o_g(I, R7), size, F0))), F0), L1), double(multiply(branch(flip(equality(index(I, corner(get_arg_rank_f(o_g(I, R7), size, L1), R0)), EIGHT)), UNITY, DOWN_LEFT), width_t(I)))))), get_arg_rank_f(o_g(I, R7), size, L1)), get_arg_rank_f(o_g(I, R7), size, F0))


def solve_508bd3b6(S, I):
    x1 = o_g(I, R7)
    x2 = get_arg_rank_f(x1, size, L1)
    x3 = corner(x2, R0)
    x4 = index(I, x3)
    x5 = equality(x4, EIGHT)
    x6 = corner(x2, R1)
    x7 = branch(x5, x3, x6)
    x8 = branch(x5, UNITY, DOWN_LEFT)
    x9 = width_t(I)
    x10 = multiply(x8, x9)
    x11 = double(x10)
    x12 = add(x7, x11)
    x13 = subtract(x7, x11)
    x14 = connect(x12, x13)
    x15 = fill(I, THREE, x14)
    x16 = get_arg_rank_f(x1, size, F0)
    x17 = paint(x15, x16)
    x18 = o_g(x17, R5)
    x19 = rbind(adjacent, x16)
    x20 = extract(x18, x19)
    x21 = get_nth_f(x20, F0)
    x22 = get_nth_t(x21, L1)
    x23 = flip(x5)
    x24 = branch(x23, UNITY, DOWN_LEFT)
    x25 = multiply(x24, x9)
    x26 = double(x25)
    x27 = add(x22, x26)
    x28 = subtract(x22, x26)
    x29 = connect(x27, x28)
    x30 = fill(x17, THREE, x29)
    x31 = paint(x30, x2)
    O = paint(x31, x16)
    return O
