def solve_1e32b0e9_one(S, I):
    return underfill(I, get_nth_f(difference(difference(palette_f(asobject(I)), palette_f(extract(partition(crop(I, ORIGIN, astuple(divide(subtract(height_t(I), TWO), THREE), divide(subtract(height_t(I), TWO), THREE)))), compose(flip, matcher(color, ZERO))))), initset(get_color_rank_t(I, F0))), F0), mapply(lbind(shift, extract(partition(crop(I, ORIGIN, astuple(divide(subtract(height_t(I), TWO), THREE), divide(subtract(height_t(I), TWO), THREE)))), compose(flip, matcher(color, ZERO)))), papply(astuple, papply(add, apply(lbind(multiply, divide(subtract(height_t(I), TWO), THREE)), apply(rbind(get_nth_f, F0), totuple(product(interval(ZERO, THREE, ONE), interval(ZERO, THREE, ONE))))), apply(rbind(get_nth_f, F0), totuple(product(interval(ZERO, THREE, ONE), interval(ZERO, THREE, ONE))))), papply(add, apply(lbind(multiply, divide(subtract(height_t(I), TWO), THREE)), apply(rbind(get_nth_f, L1), totuple(product(interval(ZERO, THREE, ONE), interval(ZERO, THREE, ONE))))), apply(rbind(get_nth_f, L1), totuple(product(interval(ZERO, THREE, ONE), interval(ZERO, THREE, ONE))))))))


def solve_1e32b0e9(S, I):
    x1 = asobject(I)
    x2 = palette_f(x1)
    x3 = height_t(I)
    x4 = subtract(x3, TWO)
    x5 = divide(x4, THREE)
    x6 = astuple(x5, x5)
    x7 = crop(I, ORIGIN, x6)
    x8 = partition(x7)
    x9 = matcher(color, ZERO)
    x10 = compose(flip, x9)
    x11 = extract(x8, x10)
    x12 = palette_f(x11)
    x13 = difference(x2, x12)
    x14 = get_color_rank_t(I, F0)
    x15 = initset(x14)
    x16 = difference(x13, x15)
    x17 = get_nth_f(x16, F0)
    x18 = lbind(shift, x11)
    x19 = lbind(multiply, x5)
    x20 = rbind(get_nth_f, F0)
    x21 = interval(ZERO, THREE, ONE)
    x22 = product(x21, x21)
    x23 = totuple(x22)
    x24 = apply(x20, x23)
    x25 = apply(x19, x24)
    x26 = papply(add, x25, x24)
    x27 = rbind(get_nth_f, L1)
    x28 = apply(x27, x23)
    x29 = apply(x19, x28)
    x30 = papply(add, x29, x28)
    x31 = papply(astuple, x26, x30)
    x32 = mapply(x18, x31)
    O = underfill(I, x17, x32)
    return O
