def solve_aba27056_one(S, I):
    return fill(fill(fill(I, FOUR, delta(mapply(toindices, o_g(I, R5)))), FOUR, mapply(lbind(shift, difference(box(mapply(toindices, o_g(I, R5))), mapply(toindices, o_g(I, R5)))), apply(lbind(multiply, position(delta(mapply(toindices, o_g(I, R5))), difference(box(mapply(toindices, o_g(I, R5))), mapply(toindices, o_g(I, R5))))), interval(ZERO, NINE, ONE)))), FOUR, mapply(fork(shoot, rbind(get_nth_f, F0), fork(subtract, rbind(get_nth_f, L1), rbind(get_nth_f, F0))), product(corners(difference(box(mapply(toindices, o_g(I, R5))), mapply(toindices, o_g(I, R5)))), sfilter_f(sfilter_f(f_ofcolor(fill(fill(I, FOUR, delta(mapply(toindices, o_g(I, R5)))), FOUR, mapply(lbind(shift, difference(box(mapply(toindices, o_g(I, R5))), mapply(toindices, o_g(I, R5)))), apply(lbind(multiply, position(delta(mapply(toindices, o_g(I, R5))), difference(box(mapply(toindices, o_g(I, R5))), mapply(toindices, o_g(I, R5))))), interval(ZERO, NINE, ONE)))), ZERO), matcher(chain(rbind(colorcount_f, ZERO), rbind(toobject, fill(fill(I, FOUR, delta(mapply(toindices, o_g(I, R5)))), FOUR, mapply(lbind(shift, difference(box(mapply(toindices, o_g(I, R5))), mapply(toindices, o_g(I, R5)))), apply(lbind(multiply, position(delta(mapply(toindices, o_g(I, R5))), difference(box(mapply(toindices, o_g(I, R5))), mapply(toindices, o_g(I, R5))))), interval(ZERO, NINE, ONE))))), dneighbors), TWO)), compose(fork(both, rbind(adjacent, mapply(toindices, o_g(I, R5))), rbind(adjacent, mapply(lbind(shift, difference(box(mapply(toindices, o_g(I, R5))), mapply(toindices, o_g(I, R5)))), apply(lbind(multiply, position(delta(mapply(toindices, o_g(I, R5))), difference(box(mapply(toindices, o_g(I, R5))), mapply(toindices, o_g(I, R5))))), interval(ZERO, NINE, ONE))))), initset)))))


def solve_aba27056(S, I):
    x1 = o_g(I, R5)
    x2 = mapply(toindices, x1)
    x3 = delta(x2)
    x4 = fill(I, FOUR, x3)
    x5 = box(x2)
    x6 = difference(x5, x2)
    x7 = lbind(shift, x6)
    x8 = position(x3, x6)
    x9 = lbind(multiply, x8)
    x10 = interval(ZERO, NINE, ONE)
    x11 = apply(x9, x10)
    x12 = mapply(x7, x11)
    x13 = fill(x4, FOUR, x12)
    x14 = rbind(get_nth_f, F0)
    x15 = rbind(get_nth_f, L1)
    x16 = fork(subtract, x15, x14)
    x17 = fork(shoot, x14, x16)
    x18 = corners(x6)
    x19 = f_ofcolor(x13, ZERO)
    x20 = rbind(colorcount_f, ZERO)
    x21 = rbind(toobject, x13)
    x22 = chain(x20, x21, dneighbors)
    x23 = matcher(x22, TWO)
    x24 = sfilter_f(x19, x23)
    x25 = rbind(adjacent, x2)
    x26 = rbind(adjacent, x12)
    x27 = fork(both, x25, x26)
    x28 = compose(x27, initset)
    x29 = sfilter_f(x24, x28)
    x30 = product(x18, x29)
    x31 = mapply(x17, x30)
    O = fill(x13, FOUR, x31)
    return O
