def solve_b527c5c6_one(S, I):
    return underfill(fill(I, TWO, mapply(fork(shoot, compose(center, rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), fork(astuple, fork(add, compose(invert, fork(equality, compose(rbind(col_row, R1), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R1))), fork(equality, compose(rbind(col_row, R0), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R0))), fork(add, compose(invert, fork(equality, compose(rbind(col_row, R2), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R2))), fork(equality, compose(rbind(col_row, R3), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R3))))), o_g(I, R1))), THREE, combine_f(mapply(fork(mapply, compose(lbind(lbind, shift), fork(shoot, compose(center, rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), fork(astuple, fork(add, compose(invert, fork(equality, compose(rbind(col_row, R1), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R1))), fork(equality, compose(rbind(col_row, R0), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R0))), fork(add, compose(invert, fork(equality, compose(rbind(col_row, R2), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R2))), fork(equality, compose(rbind(col_row, R3), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R3)))))), compose(lbind(apply, toivec), fork(rbind(interval, ONE), compose(invert, chain(decrement, rbind(get_rank, L1), shape_f)), compose(increment, chain(decrement, rbind(get_rank, L1), shape_f))))), difference(o_g(I, R1), sfilter_f(o_g(I, R1), compose(vline_i, fork(shoot, compose(center, rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), fork(astuple, fork(add, compose(invert, fork(equality, compose(rbind(col_row, R1), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R1))), fork(equality, compose(rbind(col_row, R0), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R0))), fork(add, compose(invert, fork(equality, compose(rbind(col_row, R2), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R2))), fork(equality, compose(rbind(col_row, R3), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R3))))))))), mapply(fork(mapply, compose(lbind(lbind, shift), fork(shoot, compose(center, rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), fork(astuple, fork(add, compose(invert, fork(equality, compose(rbind(col_row, R1), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R1))), fork(equality, compose(rbind(col_row, R0), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R0))), fork(add, compose(invert, fork(equality, compose(rbind(col_row, R2), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R2))), fork(equality, compose(rbind(col_row, R3), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R3)))))), compose(lbind(apply, tojvec), fork(rbind(interval, ONE), compose(invert, chain(decrement, rbind(get_rank, L1), shape_f)), compose(increment, chain(decrement, rbind(get_rank, L1), shape_f))))), sfilter_f(o_g(I, R1), compose(vline_i, fork(shoot, compose(center, rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), fork(astuple, fork(add, compose(invert, fork(equality, compose(rbind(col_row, R1), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R1))), fork(equality, compose(rbind(col_row, R0), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R0))), fork(add, compose(invert, fork(equality, compose(rbind(col_row, R2), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R2))), fork(equality, compose(rbind(col_row, R3), rbind(sfilter, matcher(rbind(get_nth_f, F0), TWO))), rbind(col_row, R3))))))))))


def solve_b527c5c6(S, I):
    x1 = rbind(get_nth_f, F0)
    x2 = matcher(x1, TWO)
    x3 = rbind(sfilter, x2)
    x4 = compose(center, x3)
    x5 = rbind(col_row, R1)
    x6 = compose(x5, x3)
    x7 = fork(equality, x6, x5)
    x8 = compose(invert, x7)
    x9 = rbind(col_row, R0)
    x10 = compose(x9, x3)
    x11 = fork(equality, x10, x9)
    x12 = fork(add, x8, x11)
    x13 = rbind(col_row, R2)
    x14 = compose(x13, x3)
    x15 = fork(equality, x14, x13)
    x16 = compose(invert, x15)
    x17 = rbind(col_row, R3)
    x18 = compose(x17, x3)
    x19 = fork(equality, x18, x17)
    x20 = fork(add, x16, x19)
    x21 = fork(astuple, x12, x20)
    x22 = fork(shoot, x4, x21)
    x23 = o_g(I, R1)
    x24 = mapply(x22, x23)
    x25 = fill(I, TWO, x24)
    x26 = lbind(lbind, shift)
    x27 = compose(x26, x22)
    x28 = lbind(apply, toivec)
    x29 = rbind(interval, ONE)
    x30 = rbind(get_rank, L1)
    x31 = chain(decrement, x30, shape_f)
    x32 = compose(invert, x31)
    x33 = compose(increment, x31)
    x34 = fork(x29, x32, x33)
    x35 = compose(x28, x34)
    x36 = fork(mapply, x27, x35)
    x37 = compose(vline_i, x22)
    x38 = sfilter_f(x23, x37)
    x39 = difference(x23, x38)
    x40 = mapply(x36, x39)
    x41 = lbind(apply, tojvec)
    x42 = compose(x41, x34)
    x43 = fork(mapply, x27, x42)
    x44 = mapply(x43, x38)
    x45 = combine_f(x40, x44)
    O = underfill(x25, THREE, x45)
    return O
