def solve_6aa20dc0_one(S, I):
    return paint(I, mapply(fork(mapply, lbind(lbind, shift), compose(lbind(occurrences, I), fork(difference, identity, fork(sfilter, identity, compose(lbind(matcher, rbind(get_nth_f, F0)), rbind(get_color_rank_f, F0)))))), rapply_f(apply(fork(compose, rbind(get_nth_f, F0), rbind(get_nth_f, L1)), product(insert(rbind(mir_rot_f, R1), insert(rbind(mir_rot_f, R3), insert(rbind(mir_rot_f, R0), insert(rbind(mir_rot_f, R2), initset(identity))))), apply(lbind(rbind, upscale_f), interval(ONE, FOUR, ONE)))), normalize(get_arg_rank_f(o_g(I, R3), numcolors_f, F0)))))


def solve_6aa20dc0(S, I):
    x1 = lbind(lbind, shift)
    x2 = lbind(occurrences, I)
    x3 = rbind(get_nth_f, F0)
    x4 = lbind(matcher, x3)
    x5 = rbind(get_color_rank_f, F0)
    x6 = compose(x4, x5)
    x7 = fork(sfilter, identity, x6)
    x8 = fork(difference, identity, x7)
    x9 = compose(x2, x8)
    x10 = fork(mapply, x1, x9)
    x11 = rbind(get_nth_f, L1)
    x12 = fork(compose, x3, x11)
    x13 = rbind(mir_rot_f, R1)
    x14 = rbind(mir_rot_f, R3)
    x15 = rbind(mir_rot_f, R0)
    x16 = rbind(mir_rot_f, R2)
    x17 = initset(identity)
    x18 = insert(x16, x17)
    x19 = insert(x15, x18)
    x20 = insert(x14, x19)
    x21 = insert(x13, x20)
    x22 = lbind(rbind, upscale_f)
    x23 = interval(ONE, FOUR, ONE)
    x24 = apply(x22, x23)
    x25 = product(x21, x24)
    x26 = apply(x12, x25)
    x27 = o_g(I, R3)
    x28 = get_arg_rank_f(x27, numcolors_f, F0)
    x29 = normalize(x28)
    x30 = rapply_f(x26, x29)
    x31 = mapply(x10, x30)
    O = paint(I, x31)
    return O
