def solve_3e980e27_one(S, I):
    return paint(I, combine_f(mapply(chain(rbind(compose, center), lbind(lbind, shift), fork(shift, identity, compose(lbind(compose, compose(invert, rbind(corner, R0))), lbind(rbind, sfilter))(lbind(contained, TWO))))(mir_rot_f(get_arg_rank_f(sfilter_f(insert(insert(astuple(THREE, invert(astuple(TEN, TEN))), initset(astuple(TWO, invert(astuple(TEN, TEN))))), o_g(I, R3)), compose(lbind(contained, TWO), palette_f)), size, F0), R2)), remove_f(get_arg_rank_f(sfilter_f(insert(insert(astuple(THREE, invert(astuple(TEN, TEN))), initset(astuple(TWO, invert(astuple(TEN, TEN))))), o_g(I, R3)), compose(lbind(contained, TWO), palette_f)), size, F0), sfilter_f(insert(insert(astuple(THREE, invert(astuple(TEN, TEN))), initset(astuple(TWO, invert(astuple(TEN, TEN))))), o_g(I, R3)), compose(lbind(contained, TWO), palette_f)))), mapply(chain(rbind(compose, center), lbind(lbind, shift), fork(shift, identity, compose(lbind(compose, compose(invert, rbind(corner, R0))), lbind(rbind, sfilter))(lbind(contained, THREE))))(get_arg_rank_f(sfilter_f(insert(insert(astuple(THREE, invert(astuple(TEN, TEN))), initset(astuple(TWO, invert(astuple(TEN, TEN))))), o_g(I, R3)), compose(lbind(contained, THREE), palette_f)), size, F0)), remove_f(get_arg_rank_f(sfilter_f(insert(insert(astuple(THREE, invert(astuple(TEN, TEN))), initset(astuple(TWO, invert(astuple(TEN, TEN))))), o_g(I, R3)), compose(lbind(contained, THREE), palette_f)), size, F0), sfilter_f(insert(insert(astuple(THREE, invert(astuple(TEN, TEN))), initset(astuple(TWO, invert(astuple(TEN, TEN))))), o_g(I, R3)), compose(lbind(contained, THREE), palette_f))))))


def solve_3e980e27(S, I):
    x1 = rbind(compose, center)
    x2 = lbind(lbind, shift)
    x3 = rbind(corner, R0)
    x4 = compose(invert, x3)
    x5 = lbind(compose, x4)
    x6 = lbind(rbind, sfilter)
    x7 = compose(x5, x6)
    x8 = lbind(contained, TWO)
    x9 = x7(x8)
    x10 = fork(shift, identity, x9)
    x11 = chain(x1, x2, x10)
    x12 = astuple(TEN, TEN)
    x13 = invert(x12)
    x14 = astuple(THREE, x13)
    x15 = astuple(TWO, x13)
    x16 = initset(x15)
    x17 = insert(x14, x16)
    x18 = o_g(I, R3)
    x19 = insert(x17, x18)
    x20 = compose(x8, palette_f)
    x21 = sfilter_f(x19, x20)
    x22 = get_arg_rank_f(x21, size, F0)
    x23 = mir_rot_f(x22, R2)
    x24 = x11(x23)
    x25 = remove_f(x22, x21)
    x26 = mapply(x24, x25)
    x27 = lbind(contained, THREE)
    x28 = x7(x27)
    x29 = fork(shift, identity, x28)
    x30 = chain(x1, x2, x29)
    x31 = compose(x27, palette_f)
    x32 = sfilter_f(x19, x31)
    x33 = get_arg_rank_f(x32, size, F0)
    x34 = x30(x33)
    x35 = remove_f(x33, x32)
    x36 = mapply(x34, x35)
    x37 = combine_f(x26, x36)
    O = paint(I, x37)
    return O
