def solve_7837ac64_one(S, I):
    return downscale(power(compose(rbind(mir_rot_t, R1), chain(lbind(apply, rbind(get_nth_f, F0)), rbind(sfilter, chain(flip, rbind(contained, interval(ZERO, height_t(subgrid(merge_f(remove_f(get_arg_rank_f(fgpartition(I), size, F0), fgpartition(I))), I)), increment(height_f(get_nth_f(colorfilter(o_g(subgrid(merge_f(remove_f(get_arg_rank_f(fgpartition(I), size, F0), fgpartition(I))), I), R4), ZERO), F0))))), rbind(get_nth_f, L1))), rbind(pair, interval(ZERO, height_t(subgrid(merge_f(remove_f(get_arg_rank_f(fgpartition(I), size, F0), fgpartition(I))), I)), ONE)))), TWO)(paint(subgrid(merge_f(remove_f(get_arg_rank_f(fgpartition(I), size, F0), fgpartition(I))), I), mapply(fork(recolor_o, compose(color, chain(rbind(toobject, subgrid(merge_f(remove_f(get_arg_rank_f(fgpartition(I), size, F0), fgpartition(I))), I)), corners, outbox)), identity), sfilter(colorfilter(o_g(subgrid(merge_f(remove_f(get_arg_rank_f(fgpartition(I), size, F0), fgpartition(I))), I), R4), ZERO), fork(both, compose(flip, chain(lbind(contained, chain(color, merge, frontiers)(I)), palette_f, chain(rbind(toobject, subgrid(merge_f(remove_f(get_arg_rank_f(fgpartition(I), size, F0), fgpartition(I))), I)), corners, outbox))), matcher(compose(numcolors_f, chain(rbind(toobject, subgrid(merge_f(remove_f(get_arg_rank_f(fgpartition(I), size, F0), fgpartition(I))), I)), corners, outbox)), ONE)))))), height_f(get_nth_f(colorfilter(o_g(subgrid(merge_f(remove_f(get_arg_rank_f(fgpartition(I), size, F0), fgpartition(I))), I), R4), ZERO), F0)))


def solve_7837ac64(S, I):
    x1 = rbind(mir_rot_t, R1)
    x2 = rbind(get_nth_f, F0)
    x3 = lbind(apply, x2)
    x4 = fgpartition(I)
    x5 = get_arg_rank_f(x4, size, F0)
    x6 = remove_f(x5, x4)
    x7 = merge_f(x6)
    x8 = subgrid(x7, I)
    x9 = height_t(x8)
    x10 = o_g(x8, R4)
    x11 = colorfilter(x10, ZERO)
    x12 = get_nth_f(x11, F0)
    x13 = height_f(x12)
    x14 = increment(x13)
    x15 = interval(ZERO, x9, x14)
    x16 = rbind(contained, x15)
    x17 = rbind(get_nth_f, L1)
    x18 = chain(flip, x16, x17)
    x19 = rbind(sfilter, x18)
    x20 = interval(ZERO, x9, ONE)
    x21 = rbind(pair, x20)
    x22 = chain(x3, x19, x21)
    x23 = compose(x1, x22)
    x24 = power(x23, TWO)
    x25 = rbind(toobject, x8)
    x26 = chain(x25, corners, outbox)
    x27 = compose(color, x26)
    x28 = fork(recolor_o, x27, identity)
    x29 = chain(color, merge, frontiers)
    x30 = x29(I)
    x31 = lbind(contained, x30)
    x32 = chain(x31, palette_f, x26)
    x33 = compose(flip, x32)
    x34 = compose(numcolors_f, x26)
    x35 = matcher(x34, ONE)
    x36 = fork(both, x33, x35)
    x37 = sfilter(x11, x36)
    x38 = mapply(x28, x37)
    x39 = paint(x8, x38)
    x40 = x24(x39)
    O = downscale(x40, x13)
    return O
