def solve_7df24a62_one(S, I):
    return fill(I, ONE, mpapply(mapply, apply(chain(lbind(lbind, shift), rbind(shift, NEG_UNITY), compose(normalize, rbind(f_ofcolor, ONE))), combine(astuple(subgrid(f_ofcolor(I, ONE), I), mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R4)), astuple(mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R5), mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R6)))), papply(sfilter, apply(fork(product, compose(lbind(rbind(interval, ONE), ZERO), chain(increment, lbind(subtract, height_t(I)), height_f)), compose(lbind(rbind(interval, ONE), ZERO), chain(increment, lbind(subtract, width_t(I)), width_f))), apply(normalize, apply(compose(rbind(shift, corner(f_ofcolor(I, ONE), R0)), rbind(f_ofcolor, FOUR)), combine(astuple(subgrid(f_ofcolor(I, ONE), I), mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R4)), astuple(mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R5), mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R6)))))), apply(lbind(compose, matcher(size, ZERO)), papply(compose, apply(lbind(rbind, difference), apply(lbind(difference, f_ofcolor(I, FOUR)), apply(compose(rbind(shift, corner(f_ofcolor(I, ONE), R0)), rbind(f_ofcolor, FOUR)), combine(astuple(subgrid(f_ofcolor(I, ONE), I), mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R4)), astuple(mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R5), mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R6)))))), apply(lbind(lbind, shift), apply(normalize, apply(compose(rbind(shift, corner(f_ofcolor(I, ONE), R0)), rbind(f_ofcolor, FOUR)), combine(astuple(subgrid(f_ofcolor(I, ONE), I), mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R4)), astuple(mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R5), mir_rot_t(subgrid(f_ofcolor(I, ONE), I), R6)))))))))))


def solve_7df24a62(S, I):
    x1 = lbind(lbind, shift)
    x2 = rbind(shift, NEG_UNITY)
    x3 = rbind(f_ofcolor, ONE)
    x4 = compose(normalize, x3)
    x5 = chain(x1, x2, x4)
    x6 = f_ofcolor(I, ONE)
    x7 = subgrid(x6, I)
    x8 = mir_rot_t(x7, R4)
    x9 = astuple(x7, x8)
    x10 = mir_rot_t(x7, R5)
    x11 = mir_rot_t(x7, R6)
    x12 = astuple(x10, x11)
    x13 = combine(x9, x12)
    x14 = apply(x5, x13)
    x15 = rbind(interval, ONE)
    x16 = lbind(x15, ZERO)
    x17 = height_t(I)
    x18 = lbind(subtract, x17)
    x19 = chain(increment, x18, height_f)
    x20 = compose(x16, x19)
    x21 = width_t(I)
    x22 = lbind(subtract, x21)
    x23 = chain(increment, x22, width_f)
    x24 = compose(x16, x23)
    x25 = fork(product, x20, x24)
    x26 = corner(x6, R0)
    x27 = rbind(shift, x26)
    x28 = rbind(f_ofcolor, FOUR)
    x29 = compose(x27, x28)
    x30 = apply(x29, x13)
    x31 = apply(normalize, x30)
    x32 = apply(x25, x31)
    x33 = matcher(size, ZERO)
    x34 = lbind(compose, x33)
    x35 = lbind(rbind, difference)
    x36 = f_ofcolor(I, FOUR)
    x37 = lbind(difference, x36)
    x38 = apply(x37, x30)
    x39 = apply(x35, x38)
    x40 = apply(x1, x31)
    x41 = papply(compose, x39, x40)
    x42 = apply(x34, x41)
    x43 = papply(sfilter, x32, x42)
    x44 = mpapply(mapply, x14, x43)
    O = fill(I, ONE, x44)
    return O
