def solve_36d67576_one(S, I):
    return paint(I, mapply(fork(mapply, compose(lbind(lbind, shift), normalize), fork(apply, chain(compose(lbind(rbind, subtract), rbind(corner, R0)), rbind(sfilter, compose(rbind(contained, astuple(TWO, FOUR)), rbind(get_nth_f, F0))), normalize), chain(lbind(occurrences, I), rbind(sfilter, compose(rbind(contained, astuple(TWO, FOUR)), rbind(get_nth_f, F0))), normalize))), rapply_t(combine(combine(astuple(rbind(mir_rot_f, R3), rbind(mir_rot_f, R1)), astuple(rbind(mir_rot_f, R0), rbind(mir_rot_f, R2))), totuple(apply(fork(compose, rbind(get_nth_f, F0), rbind(get_nth_f, L1)), product(combine(astuple(rbind(mir_rot_f, R3), rbind(mir_rot_f, R1)), astuple(rbind(mir_rot_f, R0), rbind(mir_rot_f, R2))), combine(astuple(rbind(mir_rot_f, R3), rbind(mir_rot_f, R1)), astuple(rbind(mir_rot_f, R0), rbind(mir_rot_f, R2))))))), get_arg_rank_f(o_g(I, R1), numcolors_f, F0))))


def solve_36d67576(S, I):
    x1 = lbind(lbind, shift)
    x2 = compose(x1, normalize)
    x3 = lbind(rbind, subtract)
    x4 = rbind(corner, R0)
    x5 = compose(x3, x4)
    x6 = astuple(TWO, FOUR)
    x7 = rbind(contained, x6)
    x8 = rbind(get_nth_f, F0)
    x9 = compose(x7, x8)
    x10 = rbind(sfilter, x9)
    x11 = chain(x5, x10, normalize)
    x12 = lbind(occurrences, I)
    x13 = chain(x12, x10, normalize)
    x14 = fork(apply, x11, x13)
    x15 = fork(mapply, x2, x14)
    x16 = rbind(mir_rot_f, R3)
    x17 = rbind(mir_rot_f, R1)
    x18 = astuple(x16, x17)
    x19 = rbind(mir_rot_f, R0)
    x20 = rbind(mir_rot_f, R2)
    x21 = astuple(x19, x20)
    x22 = combine(x18, x21)
    x23 = rbind(get_nth_f, L1)
    x24 = fork(compose, x8, x23)
    x25 = product(x22, x22)
    x26 = apply(x24, x25)
    x27 = totuple(x26)
    x28 = combine(x22, x27)
    x29 = o_g(I, R1)
    x30 = get_arg_rank_f(x29, numcolors_f, F0)
    x31 = rapply_t(x28, x30)
    x32 = mapply(x15, x31)
    O = paint(I, x32)
    return O
