def solve_2bcee788_one(S, I):
    return paint(replace(I, get_color_rank_t(I, F0), THREE), shift(sfilter_f(asobject(branch(hline_o(get_arg_rank_f(o_g(I, R5), size, L1)), mir_rot_t(subgrid(get_arg_rank_f(o_g(I, R5), size, F0), replace(I, get_color_rank_t(I, F0), THREE)), R0), mir_rot_t(subgrid(get_arg_rank_f(o_g(I, R5), size, F0), replace(I, get_color_rank_t(I, F0), THREE)), R2))), compose(flip, matcher(rbind(get_nth_f, F0), THREE))), add(corner(get_arg_rank_f(o_g(I, R5), size, F0), R0), multiply(shape_f(get_arg_rank_f(o_g(I, R5), size, F0)), astuple(branch(hline_o(get_arg_rank_f(o_g(I, R5), size, L1)), get_nth_t(position(get_arg_rank_f(o_g(I, R5), size, F0), get_arg_rank_f(o_g(I, R5), size, L1)), F0), ZERO), branch(hline_o(get_arg_rank_f(o_g(I, R5), size, L1)), ZERO, get_nth_t(position(get_arg_rank_f(o_g(I, R5), size, F0), get_arg_rank_f(o_g(I, R5), size, L1)), L1)))))))


def solve_2bcee788(S, I):
    x1 = get_color_rank_t(I, F0)
    x2 = replace(I, x1, THREE)
    x3 = o_g(I, R5)
    x4 = get_arg_rank_f(x3, size, L1)
    x5 = hline_o(x4)
    x6 = get_arg_rank_f(x3, size, F0)
    x7 = subgrid(x6, x2)
    x8 = mir_rot_t(x7, R0)
    x9 = mir_rot_t(x7, R2)
    x10 = branch(x5, x8, x9)
    x11 = asobject(x10)
    x12 = rbind(get_nth_f, F0)
    x13 = matcher(x12, THREE)
    x14 = compose(flip, x13)
    x15 = sfilter_f(x11, x14)
    x16 = corner(x6, R0)
    x17 = shape_f(x6)
    x18 = position(x6, x4)
    x19 = get_nth_t(x18, F0)
    x20 = branch(x5, x19, ZERO)
    x21 = get_nth_t(x18, L1)
    x22 = branch(x5, ZERO, x21)
    x23 = astuple(x20, x22)
    x24 = multiply(x17, x23)
    x25 = add(x16, x24)
    x26 = shift(x15, x25)
    O = paint(x2, x26)
    return O
