# Generated by tokpidjin/card.py

from pile import *
from gpu_env import GPUEnv as Env
from safe_dsl import _get_safe_default
from batt_gpu import batch_process_samples_gpu

def batt(task_id, S, I, C, log_path):
    s = []
    o = []
    # Pre-mutate: t1 - differ = True - solver = False - old_items = ['identity', ' p_g'] - old_hints = ['Any', 'Any']
    try:
        t1 = identity(p_g)
    except (TypeError, AttributeError, ValueError):
        t1 = _get_safe_default(identity)
    # Pre-mutate: t2 - differ = True - solver = False - old_items = ['t1', ' I'] - old_hints = None
    try:
        t2 = t1(I)
    except (TypeError, AttributeError, ValueError):
        t2 = _get_safe_default(t1)
    # Pre-mutate: t3 - differ = True - solver = False - old_items = ['t1', ' C'] - old_hints = None
    try:
        t3 = t1(C)
    except (TypeError, AttributeError, ValueError):
        t3 = _get_safe_default(t1)
    # Pre-mutate: t4 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t2'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    try:
        t4 = difference_tuple(t3, t2)
    except (TypeError, AttributeError, ValueError):
        t4 = _get_safe_default(difference_tuple)
    # Pre-mutate: t5 - differ = True - solver = False - old_items = ['size', ' t4'] - old_hints = ['Integer', 'Container']
    try:
        t5 = size(t4)
    except (TypeError, AttributeError, ValueError):
        t5 = _get_safe_default(size)
    # Pre-mutate: t6 - differ = True - solver = True - old_items = ['get_nth_t', ' t4', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    try:
        t6 = get_nth_t(t4, F0)
    except (TypeError, AttributeError, ValueError):
        t6 = _get_safe_default(get_nth_t)
    # Pre-mutate: t7 - differ = True - solver = False - old_items = ['astuple', ' t5', ' t6'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t7 = astuple(t5, t6)
    except (TypeError, AttributeError, ValueError):
        t7 = _get_safe_default(astuple)
    s.append((7, 'None', 'differ_c59e6ae069a9205b311cf67a15473d64', t7))
    # Pre-mutate: t8 - differ = True - solver = False - old_items = ['rbind', ' o_g', ' R5'] - old_hints = ['Callable', 'Callable', 'Any']
    try:
        t8 = rbind(o_g, R5)
    except (TypeError, AttributeError, ValueError):
        t8 = _get_safe_default(rbind)
    # Pre-mutate: t9 - differ = True - solver = False - old_items = ['t8', ' I'] - old_hints = None
    try:
        t9 = t8(I)
    except (TypeError, AttributeError, ValueError):
        t9 = _get_safe_default(t8)
    # Pre-mutate: t10 - differ = True - solver = False - old_items = ['t8', ' C'] - old_hints = None
    try:
        t10 = t8(C)
    except (TypeError, AttributeError, ValueError):
        t10 = _get_safe_default(t8)
    # Pre-mutate: t11 - differ = True - solver = False - old_items = ['rbind', ' sizefilter', ' ONE'] - old_hints = ['Callable', 'Callable', 'Any']
    try:
        t11 = rbind(sizefilter, ONE)
    except (TypeError, AttributeError, ValueError):
        t11 = _get_safe_default(rbind)
    # Pre-mutate: t12 - differ = True - solver = False - old_items = ['t11', ' t9'] - old_hints = None
    try:
        t12 = t11(t9)
    except (TypeError, AttributeError, ValueError):
        t12 = _get_safe_default(t11)
    # Pre-mutate: t13 - differ = True - solver = False - old_items = ['t11', ' t10'] - old_hints = None
    try:
        t13 = t11(t10)
    except (TypeError, AttributeError, ValueError):
        t13 = _get_safe_default(t11)
    # Pre-mutate: t14 - differ = True - solver = False - old_items = ['difference', ' t12', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    try:
        t14 = difference(t12, t13)
    except (TypeError, AttributeError, ValueError):
        t14 = _get_safe_default(difference)
    # Pre-mutate: t15 - differ = True - solver = False - old_items = ['size', ' t14'] - old_hints = ['Integer', 'Container']
    try:
        t15 = size(t14)
    except (TypeError, AttributeError, ValueError):
        t15 = _get_safe_default(size)
    # Pre-mutate: t16 - differ = True - solver = True - old_items = ['get_nth_f', ' t14', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    try:
        t16 = get_nth_f(t14, F1)
    except (TypeError, AttributeError, ValueError):
        t16 = _get_safe_default(get_nth_f)
    # Pre-mutate: t17 - differ = True - solver = False - old_items = ['astuple', ' t15', ' t16'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t17 = astuple(t15, t16)
    except (TypeError, AttributeError, ValueError):
        t17 = _get_safe_default(astuple)
    s.append((17, 'None', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t17))
    # Pre-mutate: t18 - differ = True - solver = False - old_items = ['difference', ' t13', ' t12'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    try:
        t18 = difference(t13, t12)
    except (TypeError, AttributeError, ValueError):
        t18 = _get_safe_default(difference)
    # Pre-mutate: t19 - differ = True - solver = False - old_items = ['size', ' t18'] - old_hints = ['Integer', 'Container']
    try:
        t19 = size(t18)
    except (TypeError, AttributeError, ValueError):
        t19 = _get_safe_default(size)
    # Pre-mutate: t20 - differ = True - solver = True - old_items = ['get_nth_f', ' t18', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    try:
        t20 = get_nth_f(t18, F0)
    except (TypeError, AttributeError, ValueError):
        t20 = _get_safe_default(get_nth_f)
    # Pre-mutate: t21 - differ = True - solver = False - old_items = ['astuple', ' t19', ' t20'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t21 = astuple(t19, t20)
    except (TypeError, AttributeError, ValueError):
        t21 = _get_safe_default(astuple)
    s.append((21, 'None', 'differ_f4a4346405e974b919a4b5a52f28e40c', t21))
    # Pre-mutate: t22 - differ = True - solver = False - old_items = ['difference_tuple', ' t2', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    try:
        t22 = difference_tuple(t2, t3)
    except (TypeError, AttributeError, ValueError):
        t22 = _get_safe_default(difference_tuple)
    # Pre-mutate: t23 - differ = True - solver = False - old_items = ['size', ' t22'] - old_hints = ['Integer', 'Container']
    try:
        t23 = size(t22)
    except (TypeError, AttributeError, ValueError):
        t23 = _get_safe_default(size)
    # Pre-mutate: t24 - differ = True - solver = True - old_items = ['get_nth_t', ' t22', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    try:
        t24 = get_nth_t(t22, F0)
    except (TypeError, AttributeError, ValueError):
        t24 = _get_safe_default(get_nth_t)
    # Pre-mutate: t25 - differ = True - solver = False - old_items = ['astuple', ' t23', ' t24'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t25 = astuple(t23, t24)
    except (TypeError, AttributeError, ValueError):
        t25 = _get_safe_default(astuple)
    s.append((25, 'None', 'differ_fc9e44c913711da609a9e25126b4b296', t25))
    # Pre-mutate: t26 - differ = False - solver = True - old_items = ['hupscale', ' I', ' THREE'] - old_hints = ['Grid', 'Grid', 'Integer']
    try:
        t26 = hupscale(I, THREE)
    except (TypeError, AttributeError, ValueError):
        t26 = _get_safe_default(hupscale)
    # Pre-mutate: t27 - differ = False - solver = True - old_items = ['vupscale', ' t26', ' THREE'] - old_hints = ['Grid', 'Grid', 'Integer']
    try:
        t27 = vupscale(t26, THREE)
    except (TypeError, AttributeError, ValueError):
        t27 = _get_safe_default(vupscale)
    # Pre-mutate: t28 - differ = False - solver = True - old_items = ['hconcat', ' I', ' I'] - old_hints = ['Grid', 'Grid', 'Grid']
    try:
        t28 = hconcat(I, I)
    except (TypeError, AttributeError, ValueError):
        t28 = _get_safe_default(hconcat)
    # Pre-mutate: t29 - differ = False - solver = True - old_items = ['hconcat', ' t28', ' I'] - old_hints = ['Grid', 'Grid', 'Grid']
    try:
        t29 = hconcat(t28, I)
    except (TypeError, AttributeError, ValueError):
        t29 = _get_safe_default(hconcat)
    # Pre-mutate: t30 - differ = False - solver = True - old_items = ['vconcat', ' t29', ' t29'] - old_hints = ['Grid', 'Grid', 'Grid']
    try:
        t30 = vconcat(t29, t29)
    except (TypeError, AttributeError, ValueError):
        t30 = _get_safe_default(vconcat)
    # Pre-mutate: t31 - differ = False - solver = True - old_items = ['vconcat', ' t30', ' t29'] - old_hints = ['Grid', 'Grid', 'Grid']
    try:
        t31 = vconcat(t30, t29)
    except (TypeError, AttributeError, ValueError):
        t31 = _get_safe_default(vconcat)
    # Pre-mutate: t32 - differ = False - solver = True - old_items = ['cellwise', ' t27', ' t31', ' ZERO'] - old_hints = ['Grid', 'Grid', 'Grid', 'Integer']
    try:
        t32 = cellwise(t27, t31, ZERO)
    except (TypeError, AttributeError, ValueError):
        t32 = _get_safe_default(cellwise)
    o.append((32, False, '007bbfb7', t32))
    # Pre-mutate: t33 - differ = True - solver = False - old_items = ['t1', ' t32'] - old_hints = None
    try:
        t33 = t1(t32)
    except (TypeError, AttributeError, ValueError):
        t33 = _get_safe_default(t1)
    # Pre-mutate: t34 - differ = True - solver = False - old_items = ['difference_tuple', ' t3', ' t33'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    try:
        t34 = difference_tuple(t3, t33)
    except (TypeError, AttributeError, ValueError):
        t34 = _get_safe_default(difference_tuple)
    # Pre-mutate: t35 - differ = True - solver = False - old_items = ['size', ' t34'] - old_hints = ['Integer', 'Container']
    try:
        t35 = size(t34)
    except (TypeError, AttributeError, ValueError):
        t35 = _get_safe_default(size)
    # Pre-mutate: t36 - differ = True - solver = True - old_items = ['get_nth_t', ' t34', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    try:
        t36 = get_nth_t(t34, F0)
    except (TypeError, AttributeError, ValueError):
        t36 = _get_safe_default(get_nth_t)
    # Pre-mutate: t37 - differ = True - solver = False - old_items = ['astuple', ' t35', ' t36'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t37 = astuple(t35, t36)
    except (TypeError, AttributeError, ValueError):
        t37 = _get_safe_default(astuple)
    s.append((37, '007bbfb7', 'differ_c59e6ae069a9205b311cf67a15473d64', t37))
    # Pre-mutate: t38 - differ = True - solver = False - old_items = ['t8', ' t32'] - old_hints = None
    try:
        t38 = t8(t32)
    except (TypeError, AttributeError, ValueError):
        t38 = _get_safe_default(t8)
    # Pre-mutate: t39 - differ = True - solver = False - old_items = ['t11', ' t38'] - old_hints = None
    try:
        t39 = t11(t38)
    except (TypeError, AttributeError, ValueError):
        t39 = _get_safe_default(t11)
    # Pre-mutate: t40 - differ = True - solver = False - old_items = ['difference', ' t39', ' t13'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    try:
        t40 = difference(t39, t13)
    except (TypeError, AttributeError, ValueError):
        t40 = _get_safe_default(difference)
    # Pre-mutate: t41 - differ = True - solver = False - old_items = ['size', ' t40'] - old_hints = ['Integer', 'Container']
    try:
        t41 = size(t40)
    except (TypeError, AttributeError, ValueError):
        t41 = _get_safe_default(size)
    # Pre-mutate: t42 - differ = True - solver = True - old_items = ['get_nth_f', ' t40', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    try:
        t42 = get_nth_f(t40, F0)
    except (TypeError, AttributeError, ValueError):
        t42 = _get_safe_default(get_nth_f)
    # Pre-mutate: t43 - differ = True - solver = False - old_items = ['astuple', ' t41', ' t42'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t43 = astuple(t41, t42)
    except (TypeError, AttributeError, ValueError):
        t43 = _get_safe_default(astuple)
    s.append((43, '007bbfb7', 'differ_d50e4f6db9fab7b53f413af7de3a35da', t43))
    # Pre-mutate: t44 - differ = True - solver = False - old_items = ['difference', ' t13', ' t39'] - old_hints = ['FrozenSet', 'FrozenSet', 'FrozenSet']
    try:
        t44 = difference(t13, t39)
    except (TypeError, AttributeError, ValueError):
        t44 = _get_safe_default(difference)
    # Pre-mutate: t45 - differ = True - solver = False - old_items = ['size', ' t44'] - old_hints = ['Integer', 'Container']
    try:
        t45 = size(t44)
    except (TypeError, AttributeError, ValueError):
        t45 = _get_safe_default(size)
    # Pre-mutate: t46 - differ = True - solver = True - old_items = ['get_nth_f', ' t44', ' F0'] - old_hints = ['Any', 'FrozenSet', 'FL']
    try:
        t46 = get_nth_f(t44, F0)
    except (TypeError, AttributeError, ValueError):
        t46 = _get_safe_default(get_nth_f)
    # Pre-mutate: t47 - differ = True - solver = False - old_items = ['astuple', ' t45', ' t46'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t47 = astuple(t45, t46)
    except (TypeError, AttributeError, ValueError):
        t47 = _get_safe_default(astuple)
    s.append((47, '007bbfb7', 'differ_f4a4346405e974b919a4b5a52f28e40c', t47))
    # Pre-mutate: t48 - differ = True - solver = False - old_items = ['difference_tuple', ' t33', ' t3'] - old_hints = ['Tuple', 'Tuple', 'Tuple']
    try:
        t48 = difference_tuple(t33, t3)
    except (TypeError, AttributeError, ValueError):
        t48 = _get_safe_default(difference_tuple)
    # Pre-mutate: t49 - differ = True - solver = False - old_items = ['size', ' t48'] - old_hints = ['Integer', 'Container']
    try:
        t49 = size(t48)
    except (TypeError, AttributeError, ValueError):
        t49 = _get_safe_default(size)
    # Pre-mutate: t50 - differ = True - solver = True - old_items = ['get_nth_t', ' t48', ' F0'] - old_hints = ['Any', 'Tuple', 'FL']
    try:
        t50 = get_nth_t(t48, F0)
    except (TypeError, AttributeError, ValueError):
        t50 = _get_safe_default(get_nth_t)
    # Pre-mutate: t51 - differ = True - solver = False - old_items = ['astuple', ' t49', ' t50'] - old_hints = ['Tuple', 'Any', 'Any']
    try:
        t51 = astuple(t49, t50)
    except (TypeError, AttributeError, ValueError):
        t51 = _get_safe_default(astuple)
    s.append((51, '007bbfb7', 'differ_fc9e44c913711da609a9e25126b4b296', t51))
    return o, s
