name: Upload Dataset to Kaggle

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  upload_to_kaggle:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Install Kaggle API
      - name: Install Kaggle API
        run: |
          python -m pip install --upgrade pip
          pip install kaggle

      - name: Check if secret is accessible
        run: echo "Secret is accessible"
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

      # Set up Kaggle API key for authentication
      - name: Set up Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}
          KAGGLE_USERNAME: pierreb4
        shell: bash

      # Check if Kaggle API is working
      - name: Check Kaggle API
        run: |
          whoami
          pwd
          kaggle datasets list
        shell: bash

      # Upload dataset to Kaggle
      - name: Upload dataset to Kaggle
        run: |
          # Create the dataset directory and zip it if necessary
          zip -r dataset.zip .  # You can adjust this based on how you want to upload
          
          # Create the dataset metadata file
          echo '{
            "title": "Tokpidjin Dataset",
            "id": "pierreb4/tokpidjin",
            "licenses": [
              {
                "name": "Apache-2.0"
              }
            ],
          }' > dataset-metadata.json

          # Create the dataset directory
          mkdir -p pierreb4/tokpidjin
          mv dataset.zip dataset-metadata.json pierreb4/tokpidjin/

          # Change to the dataset directory
          cd pierreb4/tokpidjin

          # Check the contents of the directory
          ls -la

          # Check the contents of the zip file
          unzip -l dataset.zip

          # Check the contents of the metadata file
          cat dataset-metadata.json

          # Make the dataset upload to Kaggle
          kaggle datasets create -p . --dir-mode zip --public

      # Optionally, clean up the dataset
      - name: Clean up
        run: rm -rf ~/.kaggle/kaggle.json
